In [4]:
%pip install requests

Collecting requests
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting charset_normalizer<4,>=2 (from requests)
  Using cached charset_normalizer-3.4.9-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (41 kB)
Collecting idna<4,>=2.5 (from requests)
  Using cached idna-3.18-py3-none-any.whl.metadata (6.1 kB)
Collecting urllib3<3,>=1.26 (from requests)
  Using cached urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2023.5.7 (from requests)
  Using cached certifi-2026.6.17-py3-none-any.whl.metadata (2.5 kB)
Using cached requests-2.34.2-py3-none-any.whl (73 kB)
Using cached charset_normalizer-3.4.9-cp314-cp314-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (223 kB)
Using cached idna-3.18-py3-none-any.whl (65 kB)
Using cached urllib3-2.7.0-py3-none-any.whl (131 kB)
Using cached certifi-2026.6.17-py3-none-any.whl (133 kB)
Installing collected packages: urllib3, idna, charset_normalizer, certifi, requests
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5/5 [requests]1/5 [idna]
Successfully installed certifi-2026.6.17 charset_normalizer-3.4.9 idna-3.18 requests-2.34.2 urllib3-2.7.0
Note: you may need to restart the kernel to use updated packages.

In [2]:
%pip install numpy

Collecting numpy
  Using cached numpy-2.5.1-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Using cached numpy-2.5.1-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
Installing collected packages: numpy
Successfully installed numpy-2.5.1
Note: you may need to restart the kernel to use updated packages.

In [3]:
%pip install pandas

Collecting pandas
  Using cached pandas-3.0.3-cp314-cp314-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Requirement already satisfied: numpy>=2.3.3 in ./.venv/lib/python3.14/site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.3-cp314-cp314-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
Installing collected packages: pandas
Successfully installed pandas-3.0.3
Note: you may need to restart the kernel to use updated packages.

In [38]:
import pandas as pd
import requests
import numpy as np

**Step 1: Fetch Data from API**

In [35]:
import os
from dotenv import load_dotenv


file_loaded = load_dotenv()

API_KEY = os.getenv('TMDB_API_KEY')

In [ ]:
URL = "https://api.themoviedb.org/3/movie"

movie_id = [
    0, 299534, 19995, 140607, 299536, 597, 135397,
    420818, 24428, 168259, 99861, 284054, 12445,
    181808, 330457, 351286, 109445, 321612, 260513
]

In [26]:
len(movie_id)

19

In [37]:
def fetch_data(ids):
    movies = []
    for mov_id in ids:
        url = f"{URL}/{mov_id}?api_key={API_KEY}"
        response = requests.get(url)

        if response.status_code == 200:
            movies.append(response.json())
        else:
            print(f"Error fetching ID {mov_id}:{response.status_code}")
    return movies

fetch_data(movie_id)

Error fetching ID 0:404

[{'adult': False,
  'backdrop_path': '/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg',
  'belongs_to_collection': {'id': 86311,
   'name': 'The Avengers Collection',
   'poster_path': '/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg',
   'backdrop_path': '/2UNUv4NJdC36E5myDHACBJ99EwL.jpg'},
  'budget': 356000000,
  'genres': [{'id': 12, 'name': 'Adventure'},
   {'id': 878, 'name': 'Science Fiction'},
   {'id': 28, 'name': 'Action'}],
  'homepage': 'https://www.marvel.com/movies/avengers-endgame',
  'id': 299534,
  'imdb_id': 'tt4154796',
  'origin_country': ['US'],
  'original_language': 'en',
  'original_title': 'Avengers: Endgame',
  'overview': "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
  'popularity': 26.1374,
  'poster_path': '/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg',
  'production_companies': [{'id': 420,
    'logo_path': '/hUzeosd33nzE5MCNsZxCGEKTXaQ.png',
    'name': 'Marvel Studios',
    'origin_country': 'US'}],
  'production_countries': [{'iso_3166_1': 'US',
    'name': 'United States of America'}],
  'release_date': '2019-04-24',
  'revenue': 2799439100,
  'runtime': 181,
  'softcore': False,
  'spoken_languages': [{'english_name': 'English',
    'iso_639_1': 'en',
    'name': 'English'},
   {'english_name': 'Japanese', 'iso_639_1': 'ja', 'name': '日本語'},
   {'english_name': 'Xhosa', 'iso_639_1': 'xh', 'name': ''}],
  'status': 'Released',
  'tagline': 'Avenge the fallen.',
  'title': 'Avengers: Endgame',
  'video': False,
  'vote_average': 8.239,
  'vote_count': 28020},
 {'adult': False,
  'backdrop_path': '/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg',
  'belongs_to_collection': {'id': 87096,
   'name': 'Avatar Collection',
   'poster_path': '/3C5brXxnBxfkeKWwA1Fh4xvy4wr.jpg',
   'backdrop_path': '/gxnvX9kF7RRUQYvB52dMLPgeJkt.jpg'},
  'budget': 237000000,
  'genres': [{'id': 878, 'name': 'Science Fiction'},
   {'id': 28, 'name': 'Action'},
   {'id': 12, 'name': 'Adventure'}],
  'homepage': 'https://www.avatar.com/movies/avatar',
  'id': 19995,
  'imdb_id': 'tt0499549',
  'origin_country': ['US'],
  'original_language': 'en',
  'original_title': 'Avatar',
  'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
  'popularity': 34.5188,
  'poster_path': '/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg',
  'production_companies': [{'id': 444,
    'logo_path': None,
    'name': 'Dune Entertainment',
    'origin_country': 'US'},
   {'id': 574,
    'logo_path': '/8wdmrfGcDx3TJxYiiDksLzAW4pB.png',
    'name': 'Lightstorm Entertainment',
    'origin_country': 'US'},
   {'id': 25,
    'logo_path': '/qZCc1lty5FzX30aOCVRBLzaVmcp.png',
    'name': '20th Century Fox',
    'origin_country': 'US'},
   {'id': 133789,
    'logo_path': '/bJdeIb1ET3BkyodAASVDq1x3mls.png',
    'name': 'Ingenious Film Partners',
    'origin_country': 'GB'}],
  'production_countries': [{'iso_3166_1': 'US',
    'name': 'United States of America'},
   {'iso_3166_1': 'GB', 'name': 'United Kingdom'}],
  'release_date': '2009-12-16',
  'revenue': 2923706026,
  'runtime': 162,
  'softcore': False,
  'spoken_languages': [{'english_name': 'English',
    'iso_639_1': 'en',
    'name': 'English'},
   {'english_name': 'Spanish', 'iso_639_1': 'es', 'name': 'Español'}],
  'status': 'Released',
  'tagline': 'Enter the world of Pandora.',
  'title': 'Avatar',
  'video': False,
  'vote_average': 7.609,
  'vote_count': 34218},
 {'adult': False,
  'backdrop_path': '/k6EOrckWFuz7I4z4wiRwz8zsj4H.jpg',
  'belongs_to_collection': {'id': 10,
   'name': 'Star Wars Collection',
   'poster_path': '/pWVLFh4OuejTpUaDQbB1C4zoS2p.jpg',
   'backdrop_path': '/iY2ujEY2m68OTTlPFTiHub9joHS.jpg'},
  'budget': 245000000,
  'genres': [{'id': 12, 'name': 'Adventure'},
   {'id': 28, 'name': 'Action'},
   {'id': 878, 'name': 'Science Fiction'}],
  'homepage': 'http://www.starwars.com/films/star-wars-episode-vii',
  'id': 140607,
  'imdb_id': 'tt2488496',
  'origin_country': ['US'],
  'original_language': 'en',
  'original_title': 'Star Wars: The Force Awakens',
  'overview': 'Thirty years after defeating the Galactic Empire, Han Solo and his allies face a new threat from the evil Kylo Ren and his army of Stormtroopers.',
  'popularity': 13.3072,
  'poster_path': '/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg',
  'production_companies': [{'id': 1,
    'logo_path': '/tlVSws0RvvtPBwViUyOFAO0vcQS.png',
    'name': 'Lucasfilm Ltd.',
    'origin_country': 'US'},
   {'id': 11461,
    'logo_path': '/p9FoEt5shEKRWRKVIlvFaEmRnun.png',
    'name': 'Bad Robot',
    'origin_country': 'US'}],
  'production_countries': [{'iso_3166_1': 'US',
    'name': 'United States of America'}],
  'release_date': '2015-12-15',
  'revenue': 2068223624,
  'runtime': 136,
  'softcore': False,
  'spoken_languages': [{'english_name': 'English',
    'iso_639_1': 'en',
    'name': 'English'}],
  'status': 'Released',
  'tagline': 'Every generation has a story.',
  'title': 'Star Wars: The Force Awakens',
  'video': False,
  'vote_average': 7.248,
  'vote_count': 20652},
 {'adult': False,
  'backdrop_path': '/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg',
  'belongs_to_collection': {'id': 86311,
   'name': 'The Avengers Collection',
   'poster_path': '/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg',
   'backdrop_path': '/2UNUv4NJdC36E5myDHACBJ99EwL.jpg'},
  'budget': 300000000,
  'genres': [{'id': 12, 'name': 'Adventure'},
   {'id': 28, 'name': 'Action'},
   {'id': 878, 'name': 'Science Fiction'}],
  'homepage': 'https://www.marvel.com/movies/avengers-infinity-war',
  'id': 299536,
  'imdb_id': 'tt4154756',
  'origin_country': ['US'],
  'original_language': 'en',
  'original_title': 'Avengers: Infinity War',
  'overview': 'As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.',
  'popularity': 42.5694,
  'poster_path': '/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',
  'production_companies': [{'id': 420,
    'logo_path': '/hUzeosd33nzE5MCNsZxCGEKTXaQ.png',
    'name': 'Marvel Studios',
    'origin_country': 'US'}],
  'production_countries': [{'iso_3166_1': 'US',
    'name': 'United States of America'}],
  'release_date': '2018-04-25',
  'revenue': 2052415039,
  'runtime': 149,
  'softcore': False,
  'spoken_languages': [{'english_name': 'English',
    'iso_639_1': 'en',
    'name': 'English'},
   {'english_name': 'Xhosa', 'iso_639_1': 'xh', 'name': ''}],
  'status': 'Released',
  'tagline': 'Destiny arrives all the same.',
  'title': 'Avengers: Infinity War',
  'video': False,
  'vote_average': 8.2,
  'vote_count': 32277},
 {'adult': False,
  'backdrop_path': '/xnHVX37XZEp33hhCbYlQFq7ux1J.jpg',
  'belongs_to_collection': None,
  'budget': 200000000,
  'genres': [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}],
  'homepage': 'https://www.paramountmovies.com/movies/titanic',
  'id': 597,
  'imdb_id': 'tt0120338',
  'origin_country': ['US'],
  'original_language': 'en',
  'original_title': 'Titanic',
  'overview': "101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic, 84 years later. A young Rose boards the ship with her mother and fiancé. Meanwhile, Jack Dawson and Fabrizio De Rossi win third-class tickets aboard the ship. Rose tells the whole story from Titanic's departure through to its death—on its first and last voyage—on April 15, 1912.",
  'popularity': 32.9389,
  'poster_path': '/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg',
  'production_companies': [{'id': 4,
    'logo_path': '/jay6WcMgagAklUt7i9Euwj1pzTF.png',
    'name': 'Paramount Pictures',
    'origin_country': 'US'},
   {'id': 25,
    'logo_path': '/qZCc1lty5FzX30aOCVRBLzaVmcp.png',
    'name': '20th Century Fox',
    'origin_country': 'US'},
   {'id': 574,
    'logo_path': '/8wdmrfGcDx3TJxYiiDksLzAW4pB.png',
    'name': 'Lightstorm Entertainment',
    'origin_country': 'US'}],
  'production_countries': [{'iso_3166_1': 'US',
    'name': 'United States of America'}],
  'release_date': '1997-12-18',
  'revenue': 2264162353,
  'runtime': 194,
  'softcore': False,
  'spoken_languages': [{'english_name': 'English',
    'iso_639_1': 'en',
    'name': 'English'},
   {'english_name': 'French', 'iso_639_1': 'fr', 'name': 'Français'},
   {'english_name': 'German', 'iso_639_1': 'de', 'name': 'Deutsch'},
   {'english_name': 'Swedish', 'iso_639_1': 'sv', 'name': 'svenska'},
   {'english_name': 'Italian', 'iso_639_1': 'it', 'name': 'Italiano'},
   {'english_name': 'Russian', 'iso_639_1': 'ru', 'name': 'Pусский'}],
  'status': 'Released',
  'tagline': 'Nothing on earth could come between them.',
  'title': 'Titanic',
  'video': False,
  'vote_average': 7.903,
  'vote_count': 27344},
 {'adult': False,
  'backdrop_path': '/dF6FjTZzRTENfB4R17HDN20jLT2.jpg',
  'belongs_to_collection': {'id': 328,
   'name': 'Jurassic Park Collection',
   'poster_path': '/qIm2nHXLpBBdMxi8dvfrnDkBUDh.jpg',
   'backdrop_path': '/njFixYzIxX8jsn6KMSEtAzi4avi.jpg'},
  'budget': 150000000,
  'genres': [{'id': 12, 'name': 'Adventure'},
   {'id': 878, 'name': 'Science Fiction'},
   {'id': 53, 'name': 'Thriller'}],
  'homepage': 'https://www.jurassicworld.com/',
  'id': 135397,
  'imdb_id': 'tt0369610',
  'origin_country': ['US'],
  'original_language': 'en',
  'original_title': 'Jurassic World',
  'overview': 'Twenty-two years after the events of Jurassic Park, Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.',
  'popularity': 17.6107,
  'poster_path': '/rhr4y79GpxQF9IsfJItRXVaoGs4.jpg',
  'production_companies': [{'id': 56,
    'logo_path': '/cEaxANEisCqeEoRvODv2dO1I0iI.png',
    'name': 'Amblin Entertainment',
    'origin_country': 'US'},
   {'id': 33,
    'logo_path': '/8lvHyhjr8oUKOOy2dKXoALWKdp0.png',
    'name': 'Universal Pictures',
    'origin_country': 'US'},
   {'id': 923,
    'logo_path': '/5UQsZrfbfG2dYJbx8DxfoTr2Bvu.png',
    'name': 'Legendary Pictures',
    'origin_country': 'US'}],
  'production_countries': [{'iso_3166_1': 'US',
    'name': 'United States of America'}],
  'release_date': '2015-06-06',
  'revenue': 1671537444,
  'runtime': 124,
  'softcore': False,
  'spoken_languages': [{'english_name': 'English',
    'iso_639_1': 'en',
    'name': 'English'}],
  'status': 'Released',
  'tagline': 'The park is open.',
  'title': 'Jurassic World',
  'video': False,
  'vote_average': 6.7,
  'vote_count': 21682},
 {'adult': False,
  'backdrop_path': '/1TUg5pO1VZ4B0Q1amk3OlXvlpXV.jpg',
  'belongs_to_collection': {'id': 762512,
   'name': 'The Lion King (Reboot) Collection',
   'poster_path': '/dGpIRn4Nqi63JO1RlKxjcPbQSAw.jpg',
   'backdrop_path': '/1KeXF239BkqLChcAcF8gKl1stZz.jpg'},
  'budget': 260000000,
  'genres': [{'id': 12, 'name': 'Adventure'},
   {'id': 18, 'name': 'Drama'},
   {'id': 10751, 'name': 'Family'},
   {'id': 16, 'name': 'Animation'}],
  'homepage': 'https://movies.disney.com/the-lion-king-2019',
  'id': 420818,
  'imdb_id': 'tt6105098',
  'origin_country': ['US'],
  'original_language': 'en',
  'original_title': 'The Lion King',
  'overview': "Simba idolizes his father, King Mufasa, and takes to heart his own royal destiny. But not everyone in the kingdom celebrates the new cub's arrival. Scar, Mufasa's brother—and former heir to the throne—has plans of his own. The battle for Pride Rock is ravaged with betrayal, tragedy and drama, ultimately resulting in Simba's exile. With help from a curious pair of newfound friends, Simba will have to figure out how to grow up and take back what is rightfully his.",
  'popularity': 11.9543,
  'poster_path': '/dzBtMocZuJbjLOXvrl4zGYigDzh.jpg',
  'production_companies': [{'id': 2,
    'logo_path': '/wdrCwmRnLFJhEoH8GSfymY85KHT.png',
    'name': 'Walt Disney Pictures',
    'origin_country': 'US'},
   {'id': 7297,
    'logo_path': '/l29JYQVZbTcjZXoz4CUYFpKRmM3.png',
    'name': 'Fairview Entertainment',
    'origin_country': 'US'}],
  'production_countries': [{'iso_3166_1': 'US',
    'name': 'United States of America'}],
  'release_date': '2019-07-12',
  'revenue': 1662020819,
  'runtime': 118,
  'softcore': False,
  'spoken_languages': [{'english_name': 'English',
    'iso_639_1': 'en',
    'name': 'English'}],
  'status': 'Released',
  'tagline': 'The king has returned.',
  'title': 'The Lion King',
  'video': False,
  'vote_average': 7.096,
  'vote_count': 10793},
 {'adult': False,
  'backdrop_path': '/pGFQCp12a8andfPlpnmXz44IIvY.jpg',
  'belongs_to_collection': {'id': 86311,
   'name': 'The Avengers Collection',
   'poster_path': '/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg',
   'backdrop_path': '/2UNUv4NJdC36E5myDHACBJ99EwL.jpg'},
  'budget': 220000000,
  'genres': [{'id': 878, 'name': 'Science Fiction'},
   {'id': 28, 'name': 'Action'},
   {'id': 12, 'name': 'Adventure'}],
  'homepage': 'https://www.marvel.com/movies/the-avengers',
  'id': 24428,
  'imdb_id': 'tt0848228',
  'origin_country': ['US'],
  'original_language': 'en',
  'original_title': 'The Avengers',
  'overview': 'When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins!',
  'popularity': 38.3941,
  'poster_path': '/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg',
  'production_companies': [{'id': 420,
    'logo_path': '/hUzeosd33nzE5MCNsZxCGEKTXaQ.png',
    'name': 'Marvel Studios',
    'origin_country': 'US'}],
  'production_countries': [{'iso_3166_1': 'US',
    'name': 'United States of America'}],
  'release_date': '2012-04-25',
  'revenue': 1518815515,
  'runtime': 143,
  'softcore': False,
  'spoken_languages': [{'english_name': 'English',
    'iso_639_1': 'en',
    'name': 'English'},
   {'english_name': 'Hindi', 'iso_639_1': 'hi', 'name': 'हिन्दी'},
   {'english_name': 'Russian', 'iso_639_1': 'ru', 'name': 'Pусский'}],
  'status': 'Released',
  'tagline': 'Some assembly required.',
  'title': 'The Avengers',
  'video': False,
  'vote_average': 8.056,
  'vote_count': 38744},
 {'adult': False,
  'backdrop_path': '/ehzI1mVcnHqB58NqPyQwpMqcVoz.jpg',
  'belongs_to_collection': {'id': 9485,
   'name': 'The Fast and the Furious Collection',
   'poster_path': '/zOCnMPoUxgJK1RFPfN4PcnT16gr.jpg',
   'backdrop_path': '/z5A5W3WYJc3UVEWljSGwdjDgQ0j.jpg'},
  'budget': 190000000,
  'genres': [{'id': 28, 'name': 'Action'},
   {'id': 80, 'name': 'Crime'},
   {'id': 53, 'name': 'Thriller'}],
  'homepage': 'https://www.universalpicturesathome.com/movies/furious-7',
  'id': 168259,
  'imdb_id': 'tt2820852',
  'origin_country': ['US'],
  'original_language': 'en',
  'original_title': 'Furious 7',
  'overview': 'Deckard Shaw seeks revenge against Dominic Toretto and his family for his comatose brother.',
  'popularity': 13.3904,
  'poster_path': '/ktofZ9Htrjiy0P6LEowsDaxd3Ri.jpg',
  'production_companies': [{'id': 333,
    'logo_path': '/5xUJfzPZ8jWJUDzYtIeuPO4qPIa.png',
    'name': 'Original Film',
    'origin_country': 'US'},
   {'id': 1225,
    'logo_path': '/rIxhJMR7oK8b2fMakmTfRLY2TZv.png',
    'name': 'One Race',
    'origin_country': 'US'},
   {'id': 33,
    'logo_path': '/8lvHyhjr8oUKOOy2dKXoALWKdp0.png',
    'name': 'Universal Pictures',
    'origin_country': 'US'}],
  'production_countries': [{'iso_3166_1': 'US',
    'name': 'United States of America'}],
  'release_date': '2015-04-01',
  'revenue': 1515400000,
  'runtime': 138,
  'softcore': False,
  'spoken_languages': [{'english_name': 'Arabic',
    'iso_639_1': 'ar',
    'name': 'العربية'},
   {'english_name': 'English', 'iso_639_1': 'en', 'name': 'English'},
   {'english_name': 'Spanish', 'iso_639_1': 'es', 'name': 'Español'},
   {'english_name': 'Thai', 'iso_639_1': 'th', 'name': 'ภาษาไทย'}],
  'status': 'Released',
  'tagline': 'Vengeance hits home.',
  'title': 'Furious 7',
  'video': False,
  'vote_average': 7.219,
  'vote_count': 11358},
 {'adult': False,
  'backdrop_path': '/kIBK5SKwgqIIuRKhhWrJn3XkbPq.jpg',
  'belongs_to_collection': {'id': 86311,
   'name': 'The Avengers Collection',
   'poster_path': '/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg',
   'backdrop_path': '/2UNUv4NJdC36E5myDHACBJ99EwL.jpg'},
  'budget': 235000000,
  'genres': [{'id': 28, 'name': 'Action'},
   {'id': 12, 'name': 'Adventure'},
   {'id': 878, 'name': 'Science Fiction'}],
  'homepage': 'https://www.marvel.com/movies/avengers-age-of-ultron',
  'id': 99861,
  'imdb_id': 'tt2395427',
  'origin_country': ['US'],
  'original_language': 'en',
  'original_title': 'Avengers: Age of Ultron',
  'overview': 'When Tony Stark tries to jumpstart a dormant peacekeeping program, things go awry and Earth’s Mightiest Heroes are put to the ultimate test as the fate of the planet hangs in the balance. As the villainous Ultron emerges, it is up to The Avengers to stop him from enacting his terrible plans, and soon uneasy alliances and unexpected action pave the way for an epic and unique global adventure.',
  'popularity': 18.7268,
  'poster_path': '/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg',
  'production_companies': [{'id': 420,
    'logo_path': '/hUzeosd33nzE5MCNsZxCGEKTXaQ.png',
    'name': 'Marvel Studios',
    'origin_country': 'US'}],
  'production_countries': [{'iso_3166_1': 'US',
    'name': 'United States of America'}],
  'release_date': '2015-04-22',
  'revenue': 1405403694,
  'runtime': 141,
  'softcore': False,
  'spoken_languages': [{'english_name': 'English',
    'iso_639_1': 'en',
    'name': 'English'}],
  'status': 'Released',
  'tagline': 'A new age has come.',
  'title': 'Avengers: Age of Ultron',
  'video': False,
  'vote_average': 7.3,
  'vote_count': 24598},
 {'adult': False,
  'backdrop_path': '/19Ed4XgjahPm4U8JT7SnntERIlt.jpg',
  'belongs_to_collection': {'id': 529892,
   'name': 'Black Panther Collection',
   'poster_path': '/VtMkk2s92SnDUt8eYyUyYaSJQK.jpg',
   'backdrop_path': '/nsiBzWsmmerBMuD8TKHpYBTnfhD.jpg'},
  'budget': 200000000,
  'genres': [{'id': 28, 'name': 'Action'},
   {'id': 12, 'name': 'Adventure'},
   {'id': 878, 'name': 'Science Fiction'}],
  'homepage': 'https://www.marvel.com/movies/black-panther',
  'id': 284054,
  'imdb_id': 'tt1825683',
  'origin_country': ['US'],
  'original_language': 'en',
  'original_title': 'Black Panther',
  'overview': "King T'Challa returns home to the reclusive, technologically advanced African nation of Wakanda to serve as his country's new leader. However, T'Challa soon finds that he is challenged for the throne by factions within his own country as well as without. Using powers reserved to Wakandan kings, T'Challa assumes the Black Panther mantle to join with ex-girlfriend Nakia, the queen-mother, his princess-kid sister, members of the Dora Milaje (the Wakandan 'special forces') and an American secret agent, to prevent Wakanda from being dragged into a world war.",
  'popularity': 16.3375,
  'poster_path': '/uxzzxijgPIY7slzFvMotPv8wjKA.jpg',
  'production_companies': [{'id': 420,
    'logo_path': '/hUzeosd33nzE5MCNsZxCGEKTXaQ.png',
    'name': 'Marvel Studios',
    'origin_country': 'US'}],
  'production_countries': [{'iso_3166_1': 'US',
    'name': 'United States of America'}],
  'release_date': '2018-02-13',
  'revenue': 1349926083,
  'runtime': 135,
  'softcore': False,
  'spoken_languages': [{'english_name': 'English',
    'iso_639_1': 'en',
    'name': 'English'},
   {'english_name': 'Korean', 'iso_639_1': 'ko', 'name': '한국어/조선말'},

In [9]:
fetched_movies = fetch_data(movie_id)

Error fetching ID 0:404

**convert to dataframe**

In [10]:
movies = pd.DataFrame(data=fetched_movies)

In [11]:
movies

,adult,backdrop_path,belongs_to_collection,budget,genres,homepage,id,imdb_id,origin_country,original_language,...,revenue,runtime,softcore,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",356000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",https://www.marvel.com/movies/avengers-endgame,299534,tt4154796,[US],en,...,2799439100,181,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Avenge the fallen.,Avengers: Endgame,False,8.239,28020
1,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,"{'id': 87096, 'name': 'Avatar Collection', 'po...",237000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",https://www.avatar.com/movies/avatar,19995,tt0499549,[US],en,...,2923706026,162,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Enter the world of Pandora.,Avatar,False,7.609,34218
2,False,/k6EOrckWFuz7I4z4wiRwz8zsj4H.jpg,"{'id': 10, 'name': 'Star Wars Collection', 'po...",245000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.starwars.com/films/star-wars-episod...,140607,tt2488496,[US],en,...,2068223624,136,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Every generation has a story.,Star Wars: The Force Awakens,False,7.248,20650
3,False,/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",300000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",https://www.marvel.com/movies/avengers-infinit...,299536,tt4154756,[US],en,...,2052415039,149,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Destiny arrives all the same.,Avengers: Infinity War,False,8.200,32277
4,False,/xnHVX37XZEp33hhCbYlQFq7ux1J.jpg,None,200000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",https://www.paramountmovies.com/movies/titanic,597,tt0120338,[US],en,...,2264162353,194,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Nothing on earth could come between them.,Titanic,False,7.903,27344
5,False,/dF6FjTZzRTENfB4R17HDN20jLT2.jpg,"{'id': 328, 'name': 'Jurassic Park Collection'...",150000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",https://www.jurassicworld.com/,135397,tt0369610,[US],en,...,1671537444,124,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,The park is open.,Jurassic World,False,6.700,21682
6,False,/1TUg5pO1VZ4B0Q1amk3OlXvlpXV.jpg,"{'id': 762512, 'name': 'The Lion King (Reboot)...",260000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",https://movies.disney.com/the-lion-king-2019,420818,tt6105098,[US],en,...,1662020819,118,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,The king has returned.,The Lion King,False,7.096,10793
7,False,/pGFQCp12a8andfPlpnmXz44IIvY.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",220000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",https://www.marvel.com/movies/the-avengers,24428,tt0848228,[US],en,...,1518815515,143,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Some assembly required.,The Avengers,False,8.056,38744
8,False,/ehzI1mVcnHqB58NqPyQwpMqcVoz.jpg,"{'id': 9485, 'name': 'The Fast and the Furious...",190000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",https://www.universalpicturesathome.com/movies...,168259,tt2820852,[US],en,...,1515400000,138,False,"[{'english_name': 'Arabic', 'iso_639_1': 'ar',...",Released,Vengeance hits home.,Furious 7,False,7.219,11358
9,False,/kIBK5SKwgqIIuRKhhWrJn3XkbPq.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",235000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",https://www.marvel.com/movies/avengers-age-of-...,99861,tt2395427,[US],en,...,1405403694,141,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,A new age has come.,Avengers: Age of Ultron,False,7.300,24598
10,False,/19Ed4XgjahPm4U8JT7SnntERIlt.jpg,"{'id': 529892, 'name': 'Black Panther Collecti...",200000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",https://www.marvel.com/movies/black-panther,284054,tt1825683,[US],en,...,1349926083,135,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Long live the king.,Black Panther,False,7.364,23610
11,False,/cbcpDn6XJaIGoOil1bKuskU8ds4.jpg,"{'id': 1241, 'name': 'Harry Potter Collection'...",125000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",https://www.warnerbros.com/movies/harry-potter...,12445,tt1201607,[GB],en,...,1341511219,130,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,It all ends.,Harry Potter and the Deathly Hallows: Part 2,False,8.100,22125
12,False,/bIUaCtWaRgd78SnoHJDI8TNf7Sd.jpg,"{'id': 10, 'name': 'Star Wars Collection', 'po...",300000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",https://www.starwars.com/films/star-wars-episo...,181808,tt2527336,[US],en,...,1334407706,152,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Let the past die.,Star Wars: The Last Jedi,False,6.748,16436
13,False,/AoSZyb37ljMAxw0RdeQEBHKtgcc.jpg,"{'id': 386382, 'name': 'Frozen Collection', 'p...",150000000,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",https://movies.disney.com/frozen-2,330457,tt4520988,[US],en,...,1453683476,103,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,The past is not what it seems.,Frozen II,False,7.229,10341
14,False,/6WA9stUMbIkEPxn3D5SWlA8FIi7.jpg,"{'id': 328, 'name': 'Jurassic Park Collection'...",170000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",https://www.uphe.com/movies/jurassic-world-fal...,351286,tt4881806,[US],en,...,1310469037,129,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,The park is gone.,Jurassic World: Fallen Kingdom,False,6.500,12844
15,False,/rj58WQ9ImI0mYDptXdM7euX1Wjt.jpg,"{'id': 386382, 'name': 'Frozen Collection', 'p...",150000000,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",http://movies.disney.com/frozen,109445,tt2294629,[US],en,...,1274219009,102,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Who will save the day? The ice guy? The nice g...,Frozen,False,7.249,17665
16,False,/uU1Mt4JWhDvl4vKb3AfxNsorkoM.jpg,None,160000000,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",http://movies.disney.com/beauty-and-the-beast-...,321612,tt2771200,[US],en,...,1266115964,129,False,"[{'english_name': 'French', 'iso_639_1': 'fr',...",Released,Be our guest.,Beauty and the Beast,False,6.967,16058
17,False,/mabuNsGJgRuCTuGqjFkWe1xdu19.jpg,"{'id': 468222, 'name': 'The Incredibles Collec...",200000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",https://movies.disney.com/incredibles-2,260513,tt3606756,[US],en,...,1243225667,118,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,"It's been too long, dahlings.",Incredibles 2,False,7.454,13765

In [12]:
movies.columns

Index(['adult', 'backdrop_path', 'belongs_to_collection', 'budget', 'genres',
       'homepage', 'id', 'imdb_id', 'origin_country', 'original_language',
       'original_title', 'overview', 'popularity', 'poster_path',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'softcore', 'spoken_languages', 'status',
       'tagline', 'title', 'video', 'vote_average', 'vote_count'],
      dtype='str')

Step 2: Data Cleaning and Processing

**1. Drop irrelevant columns**

In [13]:
irrelevant_cols = ['adult', 'imdb_id', 'original_title', 'video', 'homepage']
movies.drop(columns=irrelevant_cols)

,backdrop_path,belongs_to_collection,budget,genres,id,origin_country,original_language,overview,popularity,poster_path,...,release_date,revenue,runtime,softcore,spoken_languages,status,tagline,title,vote_average,vote_count
0,/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",356000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",299534,[US],en,After the devastating events of Avengers: Infi...,26.1374,/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg,...,2019-04-24,2799439100,181,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Avenge the fallen.,Avengers: Endgame,8.239,28020
1,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,"{'id': 87096, 'name': 'Avatar Collection', 'po...",237000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",19995,[US],en,"In the 22nd century, a paraplegic Marine is di...",34.5188,/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg,...,2009-12-16,2923706026,162,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Enter the world of Pandora.,Avatar,7.609,34218
2,/k6EOrckWFuz7I4z4wiRwz8zsj4H.jpg,"{'id': 10, 'name': 'Star Wars Collection', 'po...",245000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",140607,[US],en,Thirty years after defeating the Galactic Empi...,13.3072,/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg,...,2015-12-15,2068223624,136,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Every generation has a story.,Star Wars: The Force Awakens,7.248,20650
3,/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",300000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",299536,[US],en,As the Avengers and their allies have continue...,42.5694,/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg,...,2018-04-25,2052415039,149,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Destiny arrives all the same.,Avengers: Infinity War,8.200,32277
4,/xnHVX37XZEp33hhCbYlQFq7ux1J.jpg,None,200000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",597,[US],en,101-year-old Rose DeWitt Bukater tells the sto...,32.9389,/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg,...,1997-12-18,2264162353,194,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Nothing on earth could come between them.,Titanic,7.903,27344
5,/dF6FjTZzRTENfB4R17HDN20jLT2.jpg,"{'id': 328, 'name': 'Jurassic Park Collection'...",150000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",135397,[US],en,Twenty-two years after the events of Jurassic ...,17.6107,/rhr4y79GpxQF9IsfJItRXVaoGs4.jpg,...,2015-06-06,1671537444,124,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,The park is open.,Jurassic World,6.700,21682
6,/1TUg5pO1VZ4B0Q1amk3OlXvlpXV.jpg,"{'id': 762512, 'name': 'The Lion King (Reboot)...",260000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",420818,[US],en,"Simba idolizes his father, King Mufasa, and ta...",11.9543,/dzBtMocZuJbjLOXvrl4zGYigDzh.jpg,...,2019-07-12,1662020819,118,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,The king has returned.,The Lion King,7.096,10793
7,/pGFQCp12a8andfPlpnmXz44IIvY.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",220000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",24428,[US],en,When an unexpected enemy emerges and threatens...,38.3941,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,...,2012-04-25,1518815515,143,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Some assembly required.,The Avengers,8.056,38744
8,/ehzI1mVcnHqB58NqPyQwpMqcVoz.jpg,"{'id': 9485, 'name': 'The Fast and the Furious...",190000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",168259,[US],en,Deckard Shaw seeks revenge against Dominic Tor...,13.3904,/ktofZ9Htrjiy0P6LEowsDaxd3Ri.jpg,...,2015-04-01,1515400000,138,False,"[{'english_name': 'Arabic', 'iso_639_1': 'ar',...",Released,Vengeance hits home.,Furious 7,7.219,11358
9,/kIBK5SKwgqIIuRKhhWrJn3XkbPq.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",235000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",99861,[US],en,When Tony Stark tries to jumpstart a dormant p...,18.7268,/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg,...,2015-04-22,1405403694,141,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,A new age has come.,Avengers: Age of Ultron,7.300,24598
10,/19Ed4XgjahPm4U8JT7SnntERIlt.jpg,"{'id': 529892, 'name': 'Black Panther Collecti...",200000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",284054,[US],en,"King T'Challa returns home to the reclusive, t...",16.3375,/uxzzxijgPIY7slzFvMotPv8wjKA.jpg,...,2018-02-13,1349926083,135,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Long live the king.,Black Panther,7.364,23610
11,/cbcpDn6XJaIGoOil1bKuskU8ds4.jpg,"{'id': 1241, 'name': 'Harry Potter Collection'...",125000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",12445,[GB],en,"Harry, Ron and Hermione continue their quest t...",19.2562,/c54HpQmuwXjHq2C9wmoACjxoom3.jpg,...,2011-07-12,1341511219,130,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,It all ends.,Harry Potter and the Deathly Hallows: Part 2,8.100,22125
12,/bIUaCtWaRgd78SnoHJDI8TNf7Sd.jpg,"{'id': 10, 'name': 'Star Wars Collection', 'po...",300000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",181808,[US],en,Rey develops her newly discovered abilities wi...,26.4663,/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg,...,2017-12-13,1334407706,152,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Let the past die.,Star Wars: The Last Jedi,6.748,16436
13,/AoSZyb37ljMAxw0RdeQEBHKtgcc.jpg,"{'id': 386382, 'name': 'Frozen Collection', 'p...",150000000,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",330457,[US],en,"Elsa, Anna, Kristoff and Olaf head far into th...",20.5286,/mINJaa34MtknCYl5AjtNJzWj8cD.jpg,...,2019-11-20,1453683476,103,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,The past is not what it seems.,Frozen II,7.229,10341
14,/6WA9stUMbIkEPxn3D5SWlA8FIi7.jpg,"{'id': 328, 'name': 'Jurassic Park Collection'...",170000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",351286,[US],en,Three years after Jurassic World was destroyed...,12.8514,/x2Us3jR6ToMJjbcPbLimYoxf6xr.jpg,...,2018-06-06,1310469037,129,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,The park is gone.,Jurassic World: Fallen Kingdom,6.500,12844
15,/rj58WQ9ImI0mYDptXdM7euX1Wjt.jpg,"{'id': 386382, 'name': 'Frozen Collection', 'p...",150000000,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",109445,[US],en,Young princess Anna of Arendelle dreams about ...,19.8882,/itAKcobTYGpYT8Phwjd8c9hleTo.jpg,...,2013-11-20,1274219009,102,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Who will save the day? The ice guy? The nice g...,Frozen,7.249,17665
16,/uU1Mt4JWhDvl4vKb3AfxNsorkoM.jpg,None,160000000,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",321612,[US],en,A live-action adaptation of Disney's version o...,16.7348,/hKegSKIDep2ewJWPUQD7u0KqFIp.jpg,...,2017-03-16,1266115964,129,False,"[{'english_name': 'French', 'iso_639_1': 'fr',...",Released,Be our guest.,Beauty and the Beast,6.967,16058
17,/mabuNsGJgRuCTuGqjFkWe1xdu19.jpg,"{'id': 468222, 'name': 'The Incredibles Collec...",200000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",260513,[US],en,Elastigirl springs into action to save the day...,12.9358,/9lFKBtaVIhP7E2Pk0IY1CwTKTMZ.jpg,...,2018-06-14,1243225667,118,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,"It's been too long, dahlings.",Incredibles 2,7.454,13765

2.Evaluate JSON-like columns: ['belongs_to_collection', 'genres', 'production_countries', 'production_companies', 'spoken_languages']

Extract and clean data points:

4. Inspect extracted columns

Handling missing & Incorrect Data

**5. Convert Column datatypes:**

**Replace unrealistic values**

**7. Remove duplicates and drop rows with unknow**

**Keep only rows where at least 10 columns have non-NaN values**

**9. Filter to include only 'Released' movies, then drop 'status'**

**Reorder & Finalize DataFrame**

**10. Reorder columns:**

**11. Reset index**

Step 3: KPI Implementation & Analysis

Identify the Best/Worst Performing Movies

Step 4: Data Visualization