In [4]:
import pandas as pd
import requests
import numpy as np

**Step 1: Fetch Data from API**

In [8]:
import os
from dotenv import load_dotenv


file_loaded = load_dotenv()

API_KEY = os.getenv('TMDB_API_KEY')

In [5]:
API_KEY = "9d4936f3a9f3f47388d48c1078821be6"

In [6]:
URL = "https://api.themoviedb.org/3/movie"

movie_id = [
    0, 299534, 19995, 140607, 299536, 597, 135397,
    420818, 24428, 168259, 99861, 284054, 12445,
    181808, 330457, 351286, 109445, 321612, 260513
]

In [7]:
def fetch_data(ids):
    movies = []
    for mov_id in ids:
        url = f"{URL}/{mov_id}?api_key={API_KEY}"
        response = requests.get(url)

        if response.status_code == 200:
            movies.append(response.json())
        else:
            print(f"Error fetching ID {mov_id}:{response.status_code}")
    return movies

fetch_data(movie_id)

Error fetching ID 0:404

[{'adult': False,
  'backdrop_path': '/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg',
  'belongs_to_collection': {'id': 86311,
   'name': 'The Avengers Collection',
   'poster_path': '/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg',
   'backdrop_path': '/2UNUv4NJdC36E5myDHACBJ99EwL.jpg'},
  'budget': 356000000,
  'genres': [{'id': 12, 'name': 'Adventure'},
   {'id': 878, 'name': 'Science Fiction'},
   {'id': 28, 'name': 'Action'}],
  'homepage': 'https://www.marvel.com/movies/avengers-endgame',
  'id': 299534,
  'imdb_id': 'tt4154796',
  'origin_country': ['US'],
  'original_language': 'en',
  'original_title': 'Avengers: Endgame',
  'overview': "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
  'popularity': 13.9572,
  'poster_path': '/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg',
  'production_companies': [{'id': 420,
    'logo_path': '/hUzeosd33nzE5MCNsZxCGEKTXaQ.png',
    'name': 'Marvel Studios',
    'origin_country': 'US'}],
  'production_countries': [{'iso_3166_1': 'US',
    'name': 'United States of America'}],
  'release_date': '2019-04-24',
  'revenue': 2799439100,
  'runtime': 181,
  'softcore': False,
  'spoken_languages': [{'english_name': 'English',
    'iso_639_1': 'en',
    'name': 'English'},
   {'english_name': 'Japanese', 'iso_639_1': 'ja', 'name': '日本語'},
   {'english_name': 'Xhosa', 'iso_639_1': 'xh', 'name': ''}],
  'status': 'Released',
  'tagline': 'Avenge the fallen.',
  'title': 'Avengers: Endgame',
  'video': False,
  'vote_average': 8.239,
  'vote_count': 28042},
 {'adult': False,
  'backdrop_path': '/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg',
  'belongs_to_collection': {'id': 87096,
   'name': 'Avatar Collection',
   'poster_path': '/3C5brXxnBxfkeKWwA1Fh4xvy4wr.jpg',
   'backdrop_path': '/gxnvX9kF7RRUQYvB52dMLPgeJkt.jpg'},
  'budget': 237000000,
  'genres': [{'id': 878, 'name': 'Science Fiction'},
   {'id': 28, 'name': 'Action'},
   {'id': 12, 'name': 'Adventure'}],
  'homepage': 'https://www.avatar.com/movies/avatar',
  'id': 19995,
  'imdb_id': 'tt0499549',
  'origin_country': ['US'],
  'original_language': 'en',
  'original_title': 'Avatar',
  'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
  'popularity': 15.006,
  'poster_path': '/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg',
  'production_companies': [{'id': 444,
    'logo_path': None,
    'name': 'Dune Entertainment',
    'origin_country': 'US'},
   {'id': 574,
    'logo_path': '/8wdmrfGcDx3TJxYiiDksLzAW4pB.png',
    'name': 'Lightstorm Entertainment',
    'origin_country': 'US'},
   {'id': 25,
    'logo_path': '/qZCc1lty5FzX30aOCVRBLzaVmcp.png',
    'name': '20th Century Fox',
    'origin_country': 'US'},
   {'id': 133789,
    'logo_path': '/bJdeIb1ET3BkyodAASVDq1x3mls.png',
    'name': 'Ingenious Film Partners',
    'origin_country': 'GB'}],
  'production_countries': [{'iso_3166_1': 'US',
    'name': 'United States of America'},
   {'iso_3166_1': 'GB', 'name': 'United Kingdom'}],
  'release_date': '2009-12-16',
  'revenue': 2923706026,
  'runtime': 162,
  'softcore': False,
  'spoken_languages': [{'english_name': 'English',
    'iso_639_1': 'en',
    'name': 'English'},
   {'english_name': 'Spanish', 'iso_639_1': 'es', 'name': 'Español'}],
  'status': 'Released',
  'tagline': 'Enter the world of Pandora.',
  'title': 'Avatar',
  'video': False,
  'vote_average': 7.609,
  'vote_count': 34234},
 {'adult': False,
  'backdrop_path': '/k6EOrckWFuz7I4z4wiRwz8zsj4H.jpg',
  'belongs_to_collection': {'id': 10,
   'name': 'Star Wars Collection',
   'poster_path': '/pWVLFh4OuejTpUaDQbB1C4zoS2p.jpg',
   'backdrop_path': '/iY2ujEY2m68OTTlPFTiHub9joHS.jpg'},
  'budget': 245000000,
  'genres': [{'id': 12, 'name': 'Adventure'},
   {'id': 28, 'name': 'Action'},
   {'id': 878, 'name': 'Science Fiction'}],
  'homepage': 'http://www.starwars.com/films/star-wars-episode-vii',
  'id': 140607,
  'imdb_id': 'tt2488496',
  'origin_country': ['US'],
  'original_language': 'en',
  'original_title': 'Star Wars: The Force Awakens',
  'overview': 'Thirty years after defeating the Galactic Empire, Han Solo and his allies face a new threat from the evil Kylo Ren and his army of Stormtroopers.',
  'popularity': 6.879,
  'poster_path': '/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg',
  'production_companies': [{'id': 1,
    'logo_path': '/tlVSws0RvvtPBwViUyOFAO0vcQS.png',
    'name': 'Lucasfilm Ltd.',
    'origin_country': 'US'},
   {'id': 11461,
    'logo_path': '/p9FoEt5shEKRWRKVIlvFaEmRnun.png',
    'name': 'Bad Robot',
    'origin_country': 'US'}],
  'production_countries': [{'iso_3166_1': 'US',
    'name': 'United States of America'}],
  'release_date': '2015-12-15',
  'revenue': 2068223624,
  'runtime': 136,
  'softcore': False,
  'spoken_languages': [{'english_name': 'English',
    'iso_639_1': 'en',
    'name': 'English'}],
  'status': 'Released',
  'tagline': 'Every generation has a story.',
  'title': 'Star Wars: The Force Awakens',
  'video': False,
  'vote_average': 7.248,
  'vote_count': 20661},
 {'adult': False,
  'backdrop_path': '/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg',
  'belongs_to_collection': {'id': 86311,
   'name': 'The Avengers Collection',
   'poster_path': '/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg',
   'backdrop_path': '/2UNUv4NJdC36E5myDHACBJ99EwL.jpg'},
  'budget': 300000000,
  'genres': [{'id': 12, 'name': 'Adventure'},
   {'id': 28, 'name': 'Action'},
   {'id': 878, 'name': 'Science Fiction'}],
  'homepage': 'https://www.marvel.com/movies/avengers-infinity-war',
  'id': 299536,
  'imdb_id': 'tt4154756',
  'origin_country': ['US'],
  'original_language': 'en',
  'original_title': 'Avengers: Infinity War',
  'overview': 'As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.',
  'popularity': 22.6013,
  'poster_path': '/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',
  'production_companies': [{'id': 420,
    'logo_path': '/hUzeosd33nzE5MCNsZxCGEKTXaQ.png',
    'name': 'Marvel Studios',
    'origin_country': 'US'}],
  'production_countries': [{'iso_3166_1': 'US',
    'name': 'United States of America'}],
  'release_date': '2018-04-25',
  'revenue': 2052415039,
  'runtime': 149,
  'softcore': False,
  'spoken_languages': [{'english_name': 'English',
    'iso_639_1': 'en',
    'name': 'English'},
   {'english_name': 'Xhosa', 'iso_639_1': 'xh', 'name': ''}],
  'status': 'Released',
  'tagline': 'Destiny arrives all the same.',
  'title': 'Avengers: Infinity War',
  'video': False,
  'vote_average': 8.239,
  'vote_count': 32298},
 {'adult': False,
  'backdrop_path': '/xnHVX37XZEp33hhCbYlQFq7ux1J.jpg',
  'belongs_to_collection': None,
  'budget': 200000000,
  'genres': [{'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}],
  'homepage': 'https://www.paramountmovies.com/movies/titanic',
  'id': 597,
  'imdb_id': 'tt0120338',
  'origin_country': ['US'],
  'original_language': 'en',
  'original_title': 'Titanic',
  'overview': "101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic, 84 years later. A young Rose boards the ship with her mother and fiancé. Meanwhile, Jack Dawson and Fabrizio De Rossi win third-class tickets aboard the ship. Rose tells the whole story from Titanic's departure through to its death—on its first and last voyage—on April 15, 1912.",
  'popularity': 15.8007,
  'poster_path': '/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg',
  'production_companies': [{'id': 4,
    'logo_path': '/jay6WcMgagAklUt7i9Euwj1pzTF.png',
    'name': 'Paramount Pictures',
    'origin_country': 'US'},
   {'id': 25,
    'logo_path': '/qZCc1lty5FzX30aOCVRBLzaVmcp.png',
    'name': '20th Century Fox',
    'origin_country': 'US'},
   {'id': 574,
    'logo_path': '/8wdmrfGcDx3TJxYiiDksLzAW4pB.png',
    'name': 'Lightstorm Entertainment',
    'origin_country': 'US'}],
  'production_countries': [{'iso_3166_1': 'US',
    'name': 'United States of America'}],
  'release_date': '1997-12-18',
  'revenue': 2264162353,
  'runtime': 194,
  'softcore': False,
  'spoken_languages': [{'english_name': 'English',
    'iso_639_1': 'en',
    'name': 'English'},
   {'english_name': 'French', 'iso_639_1': 'fr', 'name': 'Français'},
   {'english_name': 'German', 'iso_639_1': 'de', 'name': 'Deutsch'},
   {'english_name': 'Swedish', 'iso_639_1': 'sv', 'name': 'svenska'},
   {'english_name': 'Italian', 'iso_639_1': 'it', 'name': 'Italiano'},
   {'english_name': 'Russian', 'iso_639_1': 'ru', 'name': 'Pусский'}],
  'status': 'Released',
  'tagline': 'Nothing on earth could come between them.',
  'title': 'Titanic',
  'video': False,
  'vote_average': 7.902,
  'vote_count': 27361},
 {'adult': False,
  'backdrop_path': '/dF6FjTZzRTENfB4R17HDN20jLT2.jpg',
  'belongs_to_collection': {'id': 328,
   'name': 'Jurassic Park Collection',
   'poster_path': '/qIm2nHXLpBBdMxi8dvfrnDkBUDh.jpg',
   'backdrop_path': '/njFixYzIxX8jsn6KMSEtAzi4avi.jpg'},
  'budget': 150000000,
  'genres': [{'id': 12, 'name': 'Adventure'},
   {'id': 878, 'name': 'Science Fiction'},
   {'id': 53, 'name': 'Thriller'}],
  'homepage': 'https://www.jurassicworld.com/',
  'id': 135397,
  'imdb_id': 'tt0369610',
  'origin_country': ['US'],
  'original_language': 'en',
  'original_title': 'Jurassic World',
  'overview': 'Twenty-two years after the events of Jurassic Park, Isla Nublar now features a fully functioning dinosaur theme park, Jurassic World, as originally envisioned by John Hammond.',
  'popularity': 16.9054,
  'poster_path': '/rhr4y79GpxQF9IsfJItRXVaoGs4.jpg',
  'production_companies': [{'id': 56,
    'logo_path': '/cEaxANEisCqeEoRvODv2dO1I0iI.png',
    'name': 'Amblin Entertainment',
    'origin_country': 'US'},
   {'id': 33,
    'logo_path': '/8lvHyhjr8oUKOOy2dKXoALWKdp0.png',
    'name': 'Universal Pictures',
    'origin_country': 'US'},
   {'id': 923,
    'logo_path': '/5UQsZrfbfG2dYJbx8DxfoTr2Bvu.png',
    'name': 'Legendary Pictures',
    'origin_country': 'US'}],
  'production_countries': [{'iso_3166_1': 'US',
    'name': 'United States of America'}],
  'release_date': '2015-06-06',
  'revenue': 1671537444,
  'runtime': 124,
  'softcore': False,
  'spoken_languages': [{'english_name': 'English',
    'iso_639_1': 'en',
    'name': 'English'}],
  'status': 'Released',
  'tagline': 'The park is open.',
  'title': 'Jurassic World',
  'video': False,
  'vote_average': 6.703,
  'vote_count': 21694},
 {'adult': False,
  'backdrop_path': '/1TUg5pO1VZ4B0Q1amk3OlXvlpXV.jpg',
  'belongs_to_collection': {'id': 762512,
   'name': 'The Lion King (Reboot) Collection',
   'poster_path': '/dGpIRn4Nqi63JO1RlKxjcPbQSAw.jpg',
   'backdrop_path': '/1KeXF239BkqLChcAcF8gKl1stZz.jpg'},
  'budget': 260000000,
  'genres': [{'id': 12, 'name': 'Adventure'},
   {'id': 18, 'name': 'Drama'},
   {'id': 10751, 'name': 'Family'},
   {'id': 16, 'name': 'Animation'}],
  'homepage': 'https://movies.disney.com/the-lion-king-2019',
  'id': 420818,
  'imdb_id': 'tt6105098',
  'origin_country': ['US'],
  'original_language': 'en',
  'original_title': 'The Lion King',
  'overview': "Simba idolizes his father, King Mufasa, and takes to heart his own royal destiny. But not everyone in the kingdom celebrates the new cub's arrival. Scar, Mufasa's brother—and former heir to the throne—has plans of his own. The battle for Pride Rock is ravaged with betrayal, tragedy and drama, ultimately resulting in Simba's exile. With help from a curious pair of newfound friends, Simba will have to figure out how to grow up and take back what is rightfully his.",
  'popularity': 11.8006,
  'poster_path': '/dzBtMocZuJbjLOXvrl4zGYigDzh.jpg',
  'production_companies': [{'id': 2,
    'logo_path': '/wdrCwmRnLFJhEoH8GSfymY85KHT.png',
    'name': 'Walt Disney Pictures',
    'origin_country': 'US'},
   {'id': 7297,
    'logo_path': '/l29JYQVZbTcjZXoz4CUYFpKRmM3.png',
    'name': 'Fairview Entertainment',
    'origin_country': 'US'}],
  'production_countries': [{'iso_3166_1': 'US',
    'name': 'United States of America'}],
  'release_date': '2019-07-12',
  'revenue': 1662020819,
  'runtime': 118,
  'softcore': False,
  'spoken_languages': [{'english_name': 'English',
    'iso_639_1': 'en',
    'name': 'English'}],
  'status': 'Released',
  'tagline': 'The king has returned.',
  'title': 'The Lion King',
  'video': False,
  'vote_average': 7.096,
  'vote_count': 10800},
 {'adult': False,
  'backdrop_path': '/pGFQCp12a8andfPlpnmXz44IIvY.jpg',
  'belongs_to_collection': {'id': 86311,
   'name': 'The Avengers Collection',
   'poster_path': '/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg',
   'backdrop_path': '/2UNUv4NJdC36E5myDHACBJ99EwL.jpg'},
  'budget': 220000000,
  'genres': [{'id': 878, 'name': 'Science Fiction'},
   {'id': 28, 'name': 'Action'},
   {'id': 12, 'name': 'Adventure'}],
  'homepage': 'https://www.marvel.com/movies/the-avengers',
  'id': 24428,
  'imdb_id': 'tt0848228',
  'origin_country': ['US'],
  'original_language': 'en',
  'original_title': 'The Avengers',
  'overview': 'When an unexpected enemy emerges and threatens global safety and security, Nick Fury, director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster. Spanning the globe, a daring recruitment effort begins!',
  'popularity': 27.1498,
  'poster_path': '/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg',
  'production_companies': [{'id': 420,
    'logo_path': '/hUzeosd33nzE5MCNsZxCGEKTXaQ.png',
    'name': 'Marvel Studios',
    'origin_country': 'US'}],
  'production_countries': [{'iso_3166_1': 'US',
    'name': 'United States of America'}],
  'release_date': '2012-04-25',
  'revenue': 1518815515,
  'runtime': 143,
  'softcore': False,
  'spoken_languages': [{'english_name': 'English',
    'iso_639_1': 'en',
    'name': 'English'},
   {'english_name': 'Hindi', 'iso_639_1': 'hi', 'name': 'हिन्दी'},
   {'english_name': 'Russian', 'iso_639_1': 'ru', 'name': 'Pусский'}],
  'status': 'Released',
  'tagline': 'Some assembly required.',
  'title': 'The Avengers',
  'video': False,
  'vote_average': 8.057,
  'vote_count': 38785},
 {'adult': False,
  'backdrop_path': '/ehzI1mVcnHqB58NqPyQwpMqcVoz.jpg',
  'belongs_to_collection': {'id': 9485,
   'name': 'The Fast and the Furious Collection',
   'poster_path': '/zOCnMPoUxgJK1RFPfN4PcnT16gr.jpg',
   'backdrop_path': '/z5A5W3WYJc3UVEWljSGwdjDgQ0j.jpg'},
  'budget': 190000000,
  'genres': [{'id': 28, 'name': 'Action'},
   {'id': 80, 'name': 'Crime'},
   {'id': 53, 'name': 'Thriller'}],
  'homepage': 'https://www.universalpicturesathome.com/movies/furious-7',
  'id': 168259,
  'imdb_id': 'tt2820852',
  'origin_country': ['US'],
  'original_language': 'en',
  'original_title': 'Furious 7',
  'overview': 'Deckard Shaw seeks revenge against Dominic Toretto and his family for his comatose brother.',
  'popularity': 9.5689,
  'poster_path': '/ktofZ9Htrjiy0P6LEowsDaxd3Ri.jpg',
  'production_companies': [{'id': 333,
    'logo_path': '/5xUJfzPZ8jWJUDzYtIeuPO4qPIa.png',
    'name': 'Original Film',
    'origin_country': 'US'},
   {'id': 1225,
    'logo_path': '/rIxhJMR7oK8b2fMakmTfRLY2TZv.png',
    'name': 'One Race',
    'origin_country': 'US'},
   {'id': 33,
    'logo_path': '/8lvHyhjr8oUKOOy2dKXoALWKdp0.png',
    'name': 'Universal Pictures',
    'origin_country': 'US'}],
  'production_countries': [{'iso_3166_1': 'US',
    'name': 'United States of America'}],
  'release_date': '2015-04-01',
  'revenue': 1515400000,
  'runtime': 138,
  'softcore': False,
  'spoken_languages': [{'english_name': 'Arabic',
    'iso_639_1': 'ar',
    'name': 'العربية'},
   {'english_name': 'English', 'iso_639_1': 'en', 'name': 'English'},
   {'english_name': 'Spanish', 'iso_639_1': 'es', 'name': 'Español'},
   {'english_name': 'Thai', 'iso_639_1': 'th', 'name': 'ภาษาไทย'}],
  'status': 'Released',
  'tagline': 'Vengeance hits home.',
  'title': 'Furious 7',
  'video': False,
  'vote_average': 7.218,
  'vote_count': 11363},
 {'adult': False,
  'backdrop_path': '/kIBK5SKwgqIIuRKhhWrJn3XkbPq.jpg',
  'belongs_to_collection': {'id': 86311,
   'name': 'The Avengers Collection',
   'poster_path': '/yFSIUVTCvgYrpalUktulvk3Gi5Y.jpg',
   'backdrop_path': '/2UNUv4NJdC36E5myDHACBJ99EwL.jpg'},
  'budget': 235000000,
  'genres': [{'id': 28, 'name': 'Action'},
   {'id': 12, 'name': 'Adventure'},
   {'id': 878, 'name': 'Science Fiction'}],
  'homepage': 'https://www.marvel.com/movies/avengers-age-of-ultron',
  'id': 99861,
  'imdb_id': 'tt2395427',
  'origin_country': ['US'],
  'original_language': 'en',
  'original_title': 'Avengers: Age of Ultron',
  'overview': 'When Tony Stark tries to jumpstart a dormant peacekeeping program, things go awry and Earth’s Mightiest Heroes are put to the ultimate test as the fate of the planet hangs in the balance. As the villainous Ultron emerges, it is up to The Avengers to stop him from enacting his terrible plans, and soon uneasy alliances and unexpected action pave the way for an epic and unique global adventure.',
  'popularity': 20.3748,
  'poster_path': '/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg',
  'production_companies': [{'id': 420,
    'logo_path': '/hUzeosd33nzE5MCNsZxCGEKTXaQ.png',
    'name': 'Marvel Studios',
    'origin_country': 'US'}],
  'production_countries': [{'iso_3166_1': 'US',
    'name': 'United States of America'}],
  'release_date': '2015-04-22',
  'revenue': 1405403694,
  'runtime': 141,
  'softcore': False,
  'spoken_languages': [{'english_name': 'English',
    'iso_639_1': 'en',
    'name': 'English'}],
  'status': 'Released',
  'tagline': 'A new age has come.',
  'title': 'Avengers: Age of Ultron',
  'video': False,
  'vote_average': 7.275,
  'vote_count': 24611},
 {'adult': False,
  'backdrop_path': '/19Ed4XgjahPm4U8JT7SnntERIlt.jpg',
  'belongs_to_collection': {'id': 529892,
   'name': 'Black Panther Collection',
   'poster_path': '/VtMkk2s92SnDUt8eYyUyYaSJQK.jpg',
   'backdrop_path': '/nsiBzWsmmerBMuD8TKHpYBTnfhD.jpg'},
  'budget': 200000000,
  'genres': [{'id': 28, 'name': 'Action'},
   {'id': 12, 'name': 'Adventure'},
   {'id': 878, 'name': 'Science Fiction'}],
  'homepage': 'https://www.marvel.com/movies/black-panther',
  'id': 284054,
  'imdb_id': 'tt1825683',
  'origin_country': ['US'],
  'original_language': 'en',
  'original_title': 'Black Panther',
  'overview': "King T'Challa returns home to the reclusive, technologically advanced African nation of Wakanda to serve as his country's new leader. However, T'Challa soon finds that he is challenged for the throne by factions within his own country as well as without. Using powers reserved to Wakandan kings, T'Challa assumes the Black Panther mantle to join with ex-girlfriend Nakia, the queen-mother, his princess-kid sister, members of the Dora Milaje (the Wakandan 'special forces') and an American secret agent, to prevent Wakanda from being dragged into a world war.",
  'popularity': 12.7883,
  'poster_path': '/uxzzxijgPIY7slzFvMotPv8wjKA.jpg',
  'production_companies': [{'id': 420,
    'logo_path': '/hUzeosd33nzE5MCNsZxCGEKTXaQ.png',
    'name': 'Marvel Studios',
    'origin_country': 'US'}],
  'production_countries': [{'iso_3166_1': 'US',
    'name': 'United States of America'}],
  'release_date': '2018-02-13',
  'revenue': 1349926083,
  'runtime': 135,
  'softcore': False,
  'spoken_languages': [{'english_name': 'English',
    'iso_639_1': 'en',
    'name': 'English'},
   {'english_name': 'Korean', 'iso_639_1': 'ko', 'name': '한국어/조선말'},

**Convert to dataframe**

In [8]:
movies = pd.DataFrame(data=fetch_data(movie_id))
movies

Error fetching ID 0:404

,adult,backdrop_path,belongs_to_collection,budget,genres,homepage,id,imdb_id,origin_country,original_language,...,revenue,runtime,softcore,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",356000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",https://www.marvel.com/movies/avengers-endgame,299534,tt4154796,[US],en,...,2799439100,181,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Avenge the fallen.,Avengers: Endgame,False,8.239,28042
1,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,"{'id': 87096, 'name': 'Avatar Collection', 'po...",237000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",https://www.avatar.com/movies/avatar,19995,tt0499549,[US],en,...,2923706026,162,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Enter the world of Pandora.,Avatar,False,7.609,34234
2,False,/k6EOrckWFuz7I4z4wiRwz8zsj4H.jpg,"{'id': 10, 'name': 'Star Wars Collection', 'po...",245000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.starwars.com/films/star-wars-episod...,140607,tt2488496,[US],en,...,2068223624,136,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Every generation has a story.,Star Wars: The Force Awakens,False,7.248,20661
3,False,/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",300000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",https://www.marvel.com/movies/avengers-infinit...,299536,tt4154756,[US],en,...,2052415039,149,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Destiny arrives all the same.,Avengers: Infinity War,False,8.239,32298
4,False,/xnHVX37XZEp33hhCbYlQFq7ux1J.jpg,None,200000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",https://www.paramountmovies.com/movies/titanic,597,tt0120338,[US],en,...,2264162353,194,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Nothing on earth could come between them.,Titanic,False,7.902,27361
5,False,/dF6FjTZzRTENfB4R17HDN20jLT2.jpg,"{'id': 328, 'name': 'Jurassic Park Collection'...",150000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",https://www.jurassicworld.com/,135397,tt0369610,[US],en,...,1671537444,124,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,The park is open.,Jurassic World,False,6.703,21694
6,False,/1TUg5pO1VZ4B0Q1amk3OlXvlpXV.jpg,"{'id': 762512, 'name': 'The Lion King (Reboot)...",260000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",https://movies.disney.com/the-lion-king-2019,420818,tt6105098,[US],en,...,1662020819,118,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,The king has returned.,The Lion King,False,7.096,10800
7,False,/pGFQCp12a8andfPlpnmXz44IIvY.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",220000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",https://www.marvel.com/movies/the-avengers,24428,tt0848228,[US],en,...,1518815515,143,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Some assembly required.,The Avengers,False,8.057,38785
8,False,/ehzI1mVcnHqB58NqPyQwpMqcVoz.jpg,"{'id': 9485, 'name': 'The Fast and the Furious...",190000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",https://www.universalpicturesathome.com/movies...,168259,tt2820852,[US],en,...,1515400000,138,False,"[{'english_name': 'Arabic', 'iso_639_1': 'ar',...",Released,Vengeance hits home.,Furious 7,False,7.218,11363
9,False,/kIBK5SKwgqIIuRKhhWrJn3XkbPq.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",235000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",https://www.marvel.com/movies/avengers-age-of-...,99861,tt2395427,[US],en,...,1405403694,141,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,A new age has come.,Avengers: Age of Ultron,False,7.275,24611
10,False,/19Ed4XgjahPm4U8JT7SnntERIlt.jpg,"{'id': 529892, 'name': 'Black Panther Collecti...",200000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",https://www.marvel.com/movies/black-panther,284054,tt1825683,[US],en,...,1349926083,135,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Long live the king.,Black Panther,False,7.364,23619
11,False,/cbcpDn6XJaIGoOil1bKuskU8ds4.jpg,"{'id': 1241, 'name': 'Harry Potter Collection'...",125000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",https://www.warnerbros.com/movies/harry-potter...,12445,tt1201607,[GB],en,...,1341511219,130,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,It all ends.,Harry Potter and the Deathly Hallows: Part 2,False,8.080,22138
12,False,/bIUaCtWaRgd78SnoHJDI8TNf7Sd.jpg,"{'id': 10, 'name': 'Star Wars Collection', 'po...",300000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",https://www.starwars.com/films/star-wars-episo...,181808,tt2527336,[US],en,...,1334407706,152,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Let the past die.,Star Wars: The Last Jedi,False,6.747,16444
13,False,/AoSZyb37ljMAxw0RdeQEBHKtgcc.jpg,"{'id': 386382, 'name': 'Frozen Collection', 'p...",150000000,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",https://movies.disney.com/frozen-2,330457,tt4520988,[US],en,...,1453683476,103,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,The past is not what it seems.,Frozen II,False,7.229,10346
14,False,/6WA9stUMbIkEPxn3D5SWlA8FIi7.jpg,"{'id': 328, 'name': 'Jurassic Park Collection'...",170000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",https://www.uphe.com/movies/jurassic-world-fal...,351286,tt4881806,[US],en,...,1310469037,129,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,The park is gone.,Jurassic World: Fallen Kingdom,False,6.531,12851
15,False,/rj58WQ9ImI0mYDptXdM7euX1Wjt.jpg,"{'id': 386382, 'name': 'Frozen Collection', 'p...",150000000,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",http://movies.disney.com/frozen,109445,tt2294629,[US],en,...,1274219009,102,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,Who will save the day? The ice guy? The nice g...,Frozen,False,7.249,17677
16,False,/uU1Mt4JWhDvl4vKb3AfxNsorkoM.jpg,None,160000000,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",http://movies.disney.com/beauty-and-the-beast-...,321612,tt2771200,[US],en,...,1266115964,129,False,"[{'english_name': 'French', 'iso_639_1': 'fr',...",Released,Be our guest.,Beauty and the Beast,False,7.000,16065
17,False,/mabuNsGJgRuCTuGqjFkWe1xdu19.jpg,"{'id': 468222, 'name': 'The Incredibles Collec...",200000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",https://movies.disney.com/incredibles-2,260513,tt3606756,[US],en,...,1243225667,118,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Released,"It's been too long, dahlings.",Incredibles 2,False,7.454,13773

---

**Step 2: Data Cleaning and Processing**

**1. Drop irrelevant columns**

In [9]:
irrelevant_cols = ['adult', 'imdb_id', 'original_title', 'video', 'homepage']
movies = movies.drop(columns=irrelevant_cols)

In [10]:
movies.columns

Index(['backdrop_path', 'belongs_to_collection', 'budget', 'genres', 'id',
       'origin_country', 'original_language', 'overview', 'popularity',
       'poster_path', 'production_companies', 'production_countries',
       'release_date', 'revenue', 'runtime', 'softcore', 'spoken_languages',
       'status', 'tagline', 'title', 'vote_average', 'vote_count'],
      dtype='str')

2.Evaluate JSON-like columns: ['belongs_to_collection', 'genres', 'production_countries', 'production_companies', 'spoken_languages']

In [11]:
def clean_json_list(item):
    if isinstance(item, list):
        return "|".join([i['name'] for i in item if 'name' in i])
    if isinstance(item, dict):
        return item.get('name', np.nan)
    return np.nan

movies['genres'] = movies['genres'].apply(clean_json_list)
movies['spoken_languages'] = movies['spoken_languages'].apply(clean_json_list)
movies['production_countries'] = movies['production_countries'].apply(clean_json_list)
movies['production_companies'] = movies['production_companies'].apply(clean_json_list)
movies['belongs_to_collection'] = movies['belongs_to_collection'].apply(clean_json_list)

In [14]:
movies

,backdrop_path,belongs_to_collection,budget,genres,id,origin_country,original_language,overview,popularity,poster_path,...,release_date,revenue,runtime,softcore,spoken_languages,status,tagline,title,vote_average,vote_count
0,/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg,The Avengers Collection,356000000,Adventure|Science Fiction|Action,299534,[US],en,After the devastating events of Avengers: Infi...,13.9572,/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg,...,2019-04-24,2799439100,181,False,English|日本語|,Released,Avenge the fallen.,Avengers: Endgame,8.239,28042
1,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,Avatar Collection,237000000,Science Fiction|Action|Adventure,19995,[US],en,"In the 22nd century, a paraplegic Marine is di...",15.0060,/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg,...,2009-12-16,2923706026,162,False,English|Español,Released,Enter the world of Pandora.,Avatar,7.609,34234
2,/k6EOrckWFuz7I4z4wiRwz8zsj4H.jpg,Star Wars Collection,245000000,Adventure|Action|Science Fiction,140607,[US],en,Thirty years after defeating the Galactic Empi...,6.8790,/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg,...,2015-12-15,2068223624,136,False,English,Released,Every generation has a story.,Star Wars: The Force Awakens,7.248,20661
3,/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg,The Avengers Collection,300000000,Adventure|Action|Science Fiction,299536,[US],en,As the Avengers and their allies have continue...,22.6013,/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg,...,2018-04-25,2052415039,149,False,English|,Released,Destiny arrives all the same.,Avengers: Infinity War,8.239,32298
4,/xnHVX37XZEp33hhCbYlQFq7ux1J.jpg,NaN,200000000,Drama|Romance,597,[US],en,101-year-old Rose DeWitt Bukater tells the sto...,15.8007,/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg,...,1997-12-18,2264162353,194,False,English|Français|Deutsch|svenska|Italiano|Pусский,Released,Nothing on earth could come between them.,Titanic,7.902,27361
5,/dF6FjTZzRTENfB4R17HDN20jLT2.jpg,Jurassic Park Collection,150000000,Adventure|Science Fiction|Thriller,135397,[US],en,Twenty-two years after the events of Jurassic ...,16.9054,/rhr4y79GpxQF9IsfJItRXVaoGs4.jpg,...,2015-06-06,1671537444,124,False,English,Released,The park is open.,Jurassic World,6.703,21694
6,/1TUg5pO1VZ4B0Q1amk3OlXvlpXV.jpg,The Lion King (Reboot) Collection,260000000,Adventure|Drama|Family|Animation,420818,[US],en,"Simba idolizes his father, King Mufasa, and ta...",11.8006,/dzBtMocZuJbjLOXvrl4zGYigDzh.jpg,...,2019-07-12,1662020819,118,False,English,Released,The king has returned.,The Lion King,7.096,10800
7,/pGFQCp12a8andfPlpnmXz44IIvY.jpg,The Avengers Collection,220000000,Science Fiction|Action|Adventure,24428,[US],en,When an unexpected enemy emerges and threatens...,27.1498,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,...,2012-04-25,1518815515,143,False,English|हिन्दी|Pусский,Released,Some assembly required.,The Avengers,8.057,38785
8,/ehzI1mVcnHqB58NqPyQwpMqcVoz.jpg,The Fast and the Furious Collection,190000000,Action|Crime|Thriller,168259,[US],en,Deckard Shaw seeks revenge against Dominic Tor...,9.5689,/ktofZ9Htrjiy0P6LEowsDaxd3Ri.jpg,...,2015-04-01,1515400000,138,False,العربية|English|Español|ภาษาไทย,Released,Vengeance hits home.,Furious 7,7.218,11363
9,/kIBK5SKwgqIIuRKhhWrJn3XkbPq.jpg,The Avengers Collection,235000000,Action|Adventure|Science Fiction,99861,[US],en,When Tony Stark tries to jumpstart a dormant p...,20.3748,/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg,...,2015-04-22,1405403694,141,False,English,Released,A new age has come.,Avengers: Age of Ultron,7.275,24611
10,/19Ed4XgjahPm4U8JT7SnntERIlt.jpg,Black Panther Collection,200000000,Action|Adventure|Science Fiction,284054,[US],en,"King T'Challa returns home to the reclusive, t...",12.7883,/uxzzxijgPIY7slzFvMotPv8wjKA.jpg,...,2018-02-13,1349926083,135,False,English|한국어/조선말|Kiswahili|,Released,Long live the king.,Black Panther,7.364,23619
11,/cbcpDn6XJaIGoOil1bKuskU8ds4.jpg,Harry Potter Collection,125000000,Adventure|Fantasy,12445,[GB],en,"Harry, Ron and Hermione continue their quest t...",10.3234,/c54HpQmuwXjHq2C9wmoACjxoom3.jpg,...,2011-07-12,1341511219,130,False,English,Released,It all ends.,Harry Potter and the Deathly Hallows: Part 2,8.080,22138
12,/bIUaCtWaRgd78SnoHJDI8TNf7Sd.jpg,Star Wars Collection,300000000,Adventure|Action|Science Fiction,181808,[US],en,Rey develops her newly discovered abilities wi...,20.2927,/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg,...,2017-12-13,1334407706,152,False,English,Released,Let the past die.,Star Wars: The Last Jedi,6.747,16444
13,/AoSZyb37ljMAxw0RdeQEBHKtgcc.jpg,Frozen Collection,150000000,Family|Animation|Adventure|Comedy|Fantasy,330457,[US],en,"Elsa, Anna, Kristoff and Olaf head far into th...",10.8444,/mINJaa34MtknCYl5AjtNJzWj8cD.jpg,...,2019-11-20,1453683476,103,False,English,Released,The past is not what it seems.,Frozen II,7.229,10346
14,/6WA9stUMbIkEPxn3D5SWlA8FIi7.jpg,Jurassic Park Collection,170000000,Adventure|Science Fiction|Thriller,351286,[US],en,Three years after Jurassic World was destroyed...,6.5699,/x2Us3jR6ToMJjbcPbLimYoxf6xr.jpg,...,2018-06-06,1310469037,129,False,English|Pусский,Released,The park is gone.,Jurassic World: Fallen Kingdom,6.531,12851
15,/rj58WQ9ImI0mYDptXdM7euX1Wjt.jpg,Frozen Collection,150000000,Animation|Family|Adventure|Fantasy,109445,[US],en,Young princess Anna of Arendelle dreams about ...,18.6585,/itAKcobTYGpYT8Phwjd8c9hleTo.jpg,...,2013-11-20,1274219009,102,False,English,Released,Who will save the day? The ice guy? The nice g...,Frozen,7.249,17677
16,/uU1Mt4JWhDvl4vKb3AfxNsorkoM.jpg,NaN,160000000,Family|Fantasy|Romance,321612,[US],en,A live-action adaptation of Disney's version o...,8.3216,/hKegSKIDep2ewJWPUQD7u0KqFIp.jpg,...,2017-03-16,1266115964,129,False,Français|English,Released,Be our guest.,Beauty and the Beast,7.000,16065
17,/mabuNsGJgRuCTuGqjFkWe1xdu19.jpg,The Incredibles Collection,200000000,Action|Adventure|Animation|Family,260513,[US],en,Elastigirl springs into action to save the day...,11.3073,/9lFKBtaVIhP7E2Pk0IY1CwTKTMZ.jpg,...,2018-06-14,1243225667,118,False,English,Released,"It's been too long, dahlings.",Incredibles 2,7.454,13773

#### **Handling missing & Incorrect Data**

**5. Convert Column datatypes:**

In [15]:
movies.dtypes

backdrop_path                str
belongs_to_collection        str
budget                     int64
genres                       str
id                         int64
origin_country            object
original_language            str
overview                     str
popularity               float64
poster_path                  str
production_companies         str
production_countries         str
release_date                 str
revenue                    int64
runtime                    int64
softcore                    bool
spoken_languages             str
status                       str
tagline                      str
title                        str
vote_average             float64
vote_count                 int64
dtype: object

In [17]:
movies["budget"] = pd.to_numeric(movies['budget'])
movies["id"] = pd.to_numeric(movies['id'])
movies["popularity"] = pd.to_numeric(movies['popularity'])
movies['release_date'] = pd.to_datetime(movies['release_date'])

In [18]:
movies.dtypes

backdrop_path                       str
belongs_to_collection               str
budget                            int64
genres                              str
id                                int64
origin_country                   object
original_language                   str
overview                            str
popularity                      float64
poster_path                         str
production_companies                str
production_countries                str
release_date             datetime64[us]
revenue                           int64
runtime                           int64
softcore                           bool
spoken_languages                    str
status                              str
tagline                             str
title                               str
vote_average                    float64
vote_count                        int64
dtype: object

**6. Replace unrealistic values**

In [56]:
movies[movies['budget'] == 0]

Empty DataFrame
Columns: [backdrop_path, belongs_to_collection, budget, genres, id, origin_country, original_language, overview, popularity, poster_path, production_companies, production_countries, release_date, revenue, runtime, softcore, spoken_languages, status, tagline, title, vote_average, vote_count]
Index: []

[0 rows x 22 columns]

In [20]:
for col in ['budget', 'revenue', 'runtime']:
       movies[col] = movies[col].replace(0, np.nan)

In [ ]:
# Convert bugdet and revenue to million USD

movies['budget_musd'] = movies['budget'] / 1_000_000
movies['revenue_musd'] = movies['revenue'] / 1_000_000

In [23]:
movies

,backdrop_path,belongs_to_collection,budget,genres,id,origin_country,original_language,overview,popularity,poster_path,...,runtime,softcore,spoken_languages,status,tagline,title,vote_average,vote_count,budget_musd,revenue_musd
0,/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg,The Avengers Collection,356000000,Adventure|Science Fiction|Action,299534,[US],en,After the devastating events of Avengers: Infi...,13.9572,/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg,...,181,False,English|日本語|,Released,Avenge the fallen.,Avengers: Endgame,8.239,28042,356.0,2799.439100
1,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,Avatar Collection,237000000,Science Fiction|Action|Adventure,19995,[US],en,"In the 22nd century, a paraplegic Marine is di...",15.0060,/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg,...,162,False,English|Español,Released,Enter the world of Pandora.,Avatar,7.609,34234,237.0,2923.706026
2,/k6EOrckWFuz7I4z4wiRwz8zsj4H.jpg,Star Wars Collection,245000000,Adventure|Action|Science Fiction,140607,[US],en,Thirty years after defeating the Galactic Empi...,6.8790,/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg,...,136,False,English,Released,Every generation has a story.,Star Wars: The Force Awakens,7.248,20661,245.0,2068.223624
3,/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg,The Avengers Collection,300000000,Adventure|Action|Science Fiction,299536,[US],en,As the Avengers and their allies have continue...,22.6013,/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg,...,149,False,English|,Released,Destiny arrives all the same.,Avengers: Infinity War,8.239,32298,300.0,2052.415039
4,/xnHVX37XZEp33hhCbYlQFq7ux1J.jpg,NaN,200000000,Drama|Romance,597,[US],en,101-year-old Rose DeWitt Bukater tells the sto...,15.8007,/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg,...,194,False,English|Français|Deutsch|svenska|Italiano|Pусский,Released,Nothing on earth could come between them.,Titanic,7.902,27361,200.0,2264.162353
5,/dF6FjTZzRTENfB4R17HDN20jLT2.jpg,Jurassic Park Collection,150000000,Adventure|Science Fiction|Thriller,135397,[US],en,Twenty-two years after the events of Jurassic ...,16.9054,/rhr4y79GpxQF9IsfJItRXVaoGs4.jpg,...,124,False,English,Released,The park is open.,Jurassic World,6.703,21694,150.0,1671.537444
6,/1TUg5pO1VZ4B0Q1amk3OlXvlpXV.jpg,The Lion King (Reboot) Collection,260000000,Adventure|Drama|Family|Animation,420818,[US],en,"Simba idolizes his father, King Mufasa, and ta...",11.8006,/dzBtMocZuJbjLOXvrl4zGYigDzh.jpg,...,118,False,English,Released,The king has returned.,The Lion King,7.096,10800,260.0,1662.020819
7,/pGFQCp12a8andfPlpnmXz44IIvY.jpg,The Avengers Collection,220000000,Science Fiction|Action|Adventure,24428,[US],en,When an unexpected enemy emerges and threatens...,27.1498,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,...,143,False,English|हिन्दी|Pусский,Released,Some assembly required.,The Avengers,8.057,38785,220.0,1518.815515
8,/ehzI1mVcnHqB58NqPyQwpMqcVoz.jpg,The Fast and the Furious Collection,190000000,Action|Crime|Thriller,168259,[US],en,Deckard Shaw seeks revenge against Dominic Tor...,9.5689,/ktofZ9Htrjiy0P6LEowsDaxd3Ri.jpg,...,138,False,العربية|English|Español|ภาษาไทย,Released,Vengeance hits home.,Furious 7,7.218,11363,190.0,1515.400000
9,/kIBK5SKwgqIIuRKhhWrJn3XkbPq.jpg,The Avengers Collection,235000000,Action|Adventure|Science Fiction,99861,[US],en,When Tony Stark tries to jumpstart a dormant p...,20.3748,/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg,...,141,False,English,Released,A new age has come.,Avengers: Age of Ultron,7.275,24611,235.0,1405.403694
10,/19Ed4XgjahPm4U8JT7SnntERIlt.jpg,Black Panther Collection,200000000,Action|Adventure|Science Fiction,284054,[US],en,"King T'Challa returns home to the reclusive, t...",12.7883,/uxzzxijgPIY7slzFvMotPv8wjKA.jpg,...,135,False,English|한국어/조선말|Kiswahili|,Released,Long live the king.,Black Panther,7.364,23619,200.0,1349.926083
11,/cbcpDn6XJaIGoOil1bKuskU8ds4.jpg,Harry Potter Collection,125000000,Adventure|Fantasy,12445,[GB],en,"Harry, Ron and Hermione continue their quest t...",10.3234,/c54HpQmuwXjHq2C9wmoACjxoom3.jpg,...,130,False,English,Released,It all ends.,Harry Potter and the Deathly Hallows: Part 2,8.080,22138,125.0,1341.511219
12,/bIUaCtWaRgd78SnoHJDI8TNf7Sd.jpg,Star Wars Collection,300000000,Adventure|Action|Science Fiction,181808,[US],en,Rey develops her newly discovered abilities wi...,20.2927,/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg,...,152,False,English,Released,Let the past die.,Star Wars: The Last Jedi,6.747,16444,300.0,1334.407706
13,/AoSZyb37ljMAxw0RdeQEBHKtgcc.jpg,Frozen Collection,150000000,Family|Animation|Adventure|Comedy|Fantasy,330457,[US],en,"Elsa, Anna, Kristoff and Olaf head far into th...",10.8444,/mINJaa34MtknCYl5AjtNJzWj8cD.jpg,...,103,False,English,Released,The past is not what it seems.,Frozen II,7.229,10346,150.0,1453.683476
14,/6WA9stUMbIkEPxn3D5SWlA8FIi7.jpg,Jurassic Park Collection,170000000,Adventure|Science Fiction|Thriller,351286,[US],en,Three years after Jurassic World was destroyed...,6.5699,/x2Us3jR6ToMJjbcPbLimYoxf6xr.jpg,...,129,False,English|Pусский,Released,The park is gone.,Jurassic World: Fallen Kingdom,6.531,12851,170.0,1310.469037
15,/rj58WQ9ImI0mYDptXdM7euX1Wjt.jpg,Frozen Collection,150000000,Animation|Family|Adventure|Fantasy,109445,[US],en,Young princess Anna of Arendelle dreams about ...,18.6585,/itAKcobTYGpYT8Phwjd8c9hleTo.jpg,...,102,False,English,Released,Who will save the day? The ice guy? The nice g...,Frozen,7.249,17677,150.0,1274.219009
16,/uU1Mt4JWhDvl4vKb3AfxNsorkoM.jpg,NaN,160000000,Family|Fantasy|Romance,321612,[US],en,A live-action adaptation of Disney's version o...,8.3216,/hKegSKIDep2ewJWPUQD7u0KqFIp.jpg,...,129,False,Français|English,Released,Be our guest.,Beauty and the Beast,7.000,16065,160.0,1266.115964
17,/mabuNsGJgRuCTuGqjFkWe1xdu19.jpg,The Incredibles Collection,200000000,Action|Adventure|Animation|Family,260513,[US],en,Elastigirl springs into action to save the day...,11.3073,/9lFKBtaVIhP7E2Pk0IY1CwTKTMZ.jpg,...,118,False,English,Released,"It's been too long, dahlings.",Incredibles 2,7.454,13773,200.0,1243.225667

In [25]:
movies.loc[movies['vote_count'] == 0, 'vote_average'] = np.nan
movies['overview'].replace('No Data', np.nan, inplace=True)
movies['tagline'].replace('No Data', np.nan, inplace=True)

/tmp/ipykernel_22904/2290435162.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  movies['overview'].replace('No Data', np.nan, inplace=True)
/tmp/ipykernel_22904/2290435162.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  movies['tagline'].replace('No Data', np.nan, inplace=True)

0                                    Avenge the fallen.
1                           Enter the world of Pandora.
2                         Every generation has a story.
3                         Destiny arrives all the same.
4             Nothing on earth could come between them.
5                                     The park is open.
6                                The king has returned.
7                               Some assembly required.
8                                  Vengeance hits home.
9                                   A new age has come.
10                                  Long live the king.
11                                         It all ends.
12                                    Let the past die.
13                       The past is not what it seems.
14                                    The park is gone.
15    Who will save the day? The ice guy? The nice g...
16                                        Be our guest.
17                        It's been too long, dahlings.
Name: tagline, dtype: str

**7. Remove duplicates and drop rows with unknow id or title**

In [28]:
movies.drop_duplicates(subset=['id', 'title'], inplace=True)
movies.dropna(subset=['id', 'title'], inplace=True)

**Keep only rows where at least 10 columns have non-NaN values**

In [30]:
movies = movies[movies.notna().sum(axis=1) >= 10]

In [31]:
movies

,backdrop_path,belongs_to_collection,budget,genres,id,origin_country,original_language,overview,popularity,poster_path,...,runtime,softcore,spoken_languages,status,tagline,title,vote_average,vote_count,budget_musd,revenue_musd
0,/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg,The Avengers Collection,356000000,Adventure|Science Fiction|Action,299534,[US],en,After the devastating events of Avengers: Infi...,13.9572,/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg,...,181,False,English|日本語|,Released,Avenge the fallen.,Avengers: Endgame,8.239,28042,356.0,2799.439100
1,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,Avatar Collection,237000000,Science Fiction|Action|Adventure,19995,[US],en,"In the 22nd century, a paraplegic Marine is di...",15.0060,/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg,...,162,False,English|Español,Released,Enter the world of Pandora.,Avatar,7.609,34234,237.0,2923.706026
2,/k6EOrckWFuz7I4z4wiRwz8zsj4H.jpg,Star Wars Collection,245000000,Adventure|Action|Science Fiction,140607,[US],en,Thirty years after defeating the Galactic Empi...,6.8790,/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg,...,136,False,English,Released,Every generation has a story.,Star Wars: The Force Awakens,7.248,20661,245.0,2068.223624
3,/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg,The Avengers Collection,300000000,Adventure|Action|Science Fiction,299536,[US],en,As the Avengers and their allies have continue...,22.6013,/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg,...,149,False,English|,Released,Destiny arrives all the same.,Avengers: Infinity War,8.239,32298,300.0,2052.415039
4,/xnHVX37XZEp33hhCbYlQFq7ux1J.jpg,NaN,200000000,Drama|Romance,597,[US],en,101-year-old Rose DeWitt Bukater tells the sto...,15.8007,/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg,...,194,False,English|Français|Deutsch|svenska|Italiano|Pусский,Released,Nothing on earth could come between them.,Titanic,7.902,27361,200.0,2264.162353
5,/dF6FjTZzRTENfB4R17HDN20jLT2.jpg,Jurassic Park Collection,150000000,Adventure|Science Fiction|Thriller,135397,[US],en,Twenty-two years after the events of Jurassic ...,16.9054,/rhr4y79GpxQF9IsfJItRXVaoGs4.jpg,...,124,False,English,Released,The park is open.,Jurassic World,6.703,21694,150.0,1671.537444
6,/1TUg5pO1VZ4B0Q1amk3OlXvlpXV.jpg,The Lion King (Reboot) Collection,260000000,Adventure|Drama|Family|Animation,420818,[US],en,"Simba idolizes his father, King Mufasa, and ta...",11.8006,/dzBtMocZuJbjLOXvrl4zGYigDzh.jpg,...,118,False,English,Released,The king has returned.,The Lion King,7.096,10800,260.0,1662.020819
7,/pGFQCp12a8andfPlpnmXz44IIvY.jpg,The Avengers Collection,220000000,Science Fiction|Action|Adventure,24428,[US],en,When an unexpected enemy emerges and threatens...,27.1498,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,...,143,False,English|हिन्दी|Pусский,Released,Some assembly required.,The Avengers,8.057,38785,220.0,1518.815515
8,/ehzI1mVcnHqB58NqPyQwpMqcVoz.jpg,The Fast and the Furious Collection,190000000,Action|Crime|Thriller,168259,[US],en,Deckard Shaw seeks revenge against Dominic Tor...,9.5689,/ktofZ9Htrjiy0P6LEowsDaxd3Ri.jpg,...,138,False,العربية|English|Español|ภาษาไทย,Released,Vengeance hits home.,Furious 7,7.218,11363,190.0,1515.400000
9,/kIBK5SKwgqIIuRKhhWrJn3XkbPq.jpg,The Avengers Collection,235000000,Action|Adventure|Science Fiction,99861,[US],en,When Tony Stark tries to jumpstart a dormant p...,20.3748,/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg,...,141,False,English,Released,A new age has come.,Avengers: Age of Ultron,7.275,24611,235.0,1405.403694
10,/19Ed4XgjahPm4U8JT7SnntERIlt.jpg,Black Panther Collection,200000000,Action|Adventure|Science Fiction,284054,[US],en,"King T'Challa returns home to the reclusive, t...",12.7883,/uxzzxijgPIY7slzFvMotPv8wjKA.jpg,...,135,False,English|한국어/조선말|Kiswahili|,Released,Long live the king.,Black Panther,7.364,23619,200.0,1349.926083
11,/cbcpDn6XJaIGoOil1bKuskU8ds4.jpg,Harry Potter Collection,125000000,Adventure|Fantasy,12445,[GB],en,"Harry, Ron and Hermione continue their quest t...",10.3234,/c54HpQmuwXjHq2C9wmoACjxoom3.jpg,...,130,False,English,Released,It all ends.,Harry Potter and the Deathly Hallows: Part 2,8.080,22138,125.0,1341.511219
12,/bIUaCtWaRgd78SnoHJDI8TNf7Sd.jpg,Star Wars Collection,300000000,Adventure|Action|Science Fiction,181808,[US],en,Rey develops her newly discovered abilities wi...,20.2927,/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg,...,152,False,English,Released,Let the past die.,Star Wars: The Last Jedi,6.747,16444,300.0,1334.407706
13,/AoSZyb37ljMAxw0RdeQEBHKtgcc.jpg,Frozen Collection,150000000,Family|Animation|Adventure|Comedy|Fantasy,330457,[US],en,"Elsa, Anna, Kristoff and Olaf head far into th...",10.8444,/mINJaa34MtknCYl5AjtNJzWj8cD.jpg,...,103,False,English,Released,The past is not what it seems.,Frozen II,7.229,10346,150.0,1453.683476
14,/6WA9stUMbIkEPxn3D5SWlA8FIi7.jpg,Jurassic Park Collection,170000000,Adventure|Science Fiction|Thriller,351286,[US],en,Three years after Jurassic World was destroyed...,6.5699,/x2Us3jR6ToMJjbcPbLimYoxf6xr.jpg,...,129,False,English|Pусский,Released,The park is gone.,Jurassic World: Fallen Kingdom,6.531,12851,170.0,1310.469037
15,/rj58WQ9ImI0mYDptXdM7euX1Wjt.jpg,Frozen Collection,150000000,Animation|Family|Adventure|Fantasy,109445,[US],en,Young princess Anna of Arendelle dreams about ...,18.6585,/itAKcobTYGpYT8Phwjd8c9hleTo.jpg,...,102,False,English,Released,Who will save the day? The ice guy? The nice g...,Frozen,7.249,17677,150.0,1274.219009
16,/uU1Mt4JWhDvl4vKb3AfxNsorkoM.jpg,NaN,160000000,Family|Fantasy|Romance,321612,[US],en,A live-action adaptation of Disney's version o...,8.3216,/hKegSKIDep2ewJWPUQD7u0KqFIp.jpg,...,129,False,Français|English,Released,Be our guest.,Beauty and the Beast,7.000,16065,160.0,1266.115964
17,/mabuNsGJgRuCTuGqjFkWe1xdu19.jpg,The Incredibles Collection,200000000,Action|Adventure|Animation|Family,260513,[US],en,Elastigirl springs into action to save the day...,11.3073,/9lFKBtaVIhP7E2Pk0IY1CwTKTMZ.jpg,...,118,False,English,Released,"It's been too long, dahlings.",Incredibles 2,7.454,13773,200.0,1243.225667

**9. Filter to include only 'Released' movies, then drop 'status'**

In [32]:
movies = movies[movies['status'] == "Released"]

In [33]:
movies

,backdrop_path,belongs_to_collection,budget,genres,id,origin_country,original_language,overview,popularity,poster_path,...,runtime,softcore,spoken_languages,status,tagline,title,vote_average,vote_count,budget_musd,revenue_musd
0,/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg,The Avengers Collection,356000000,Adventure|Science Fiction|Action,299534,[US],en,After the devastating events of Avengers: Infi...,13.9572,/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg,...,181,False,English|日本語|,Released,Avenge the fallen.,Avengers: Endgame,8.239,28042,356.0,2799.439100
1,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,Avatar Collection,237000000,Science Fiction|Action|Adventure,19995,[US],en,"In the 22nd century, a paraplegic Marine is di...",15.0060,/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg,...,162,False,English|Español,Released,Enter the world of Pandora.,Avatar,7.609,34234,237.0,2923.706026
2,/k6EOrckWFuz7I4z4wiRwz8zsj4H.jpg,Star Wars Collection,245000000,Adventure|Action|Science Fiction,140607,[US],en,Thirty years after defeating the Galactic Empi...,6.8790,/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg,...,136,False,English,Released,Every generation has a story.,Star Wars: The Force Awakens,7.248,20661,245.0,2068.223624
3,/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg,The Avengers Collection,300000000,Adventure|Action|Science Fiction,299536,[US],en,As the Avengers and their allies have continue...,22.6013,/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg,...,149,False,English|,Released,Destiny arrives all the same.,Avengers: Infinity War,8.239,32298,300.0,2052.415039
4,/xnHVX37XZEp33hhCbYlQFq7ux1J.jpg,NaN,200000000,Drama|Romance,597,[US],en,101-year-old Rose DeWitt Bukater tells the sto...,15.8007,/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg,...,194,False,English|Français|Deutsch|svenska|Italiano|Pусский,Released,Nothing on earth could come between them.,Titanic,7.902,27361,200.0,2264.162353
5,/dF6FjTZzRTENfB4R17HDN20jLT2.jpg,Jurassic Park Collection,150000000,Adventure|Science Fiction|Thriller,135397,[US],en,Twenty-two years after the events of Jurassic ...,16.9054,/rhr4y79GpxQF9IsfJItRXVaoGs4.jpg,...,124,False,English,Released,The park is open.,Jurassic World,6.703,21694,150.0,1671.537444
6,/1TUg5pO1VZ4B0Q1amk3OlXvlpXV.jpg,The Lion King (Reboot) Collection,260000000,Adventure|Drama|Family|Animation,420818,[US],en,"Simba idolizes his father, King Mufasa, and ta...",11.8006,/dzBtMocZuJbjLOXvrl4zGYigDzh.jpg,...,118,False,English,Released,The king has returned.,The Lion King,7.096,10800,260.0,1662.020819
7,/pGFQCp12a8andfPlpnmXz44IIvY.jpg,The Avengers Collection,220000000,Science Fiction|Action|Adventure,24428,[US],en,When an unexpected enemy emerges and threatens...,27.1498,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,...,143,False,English|हिन्दी|Pусский,Released,Some assembly required.,The Avengers,8.057,38785,220.0,1518.815515
8,/ehzI1mVcnHqB58NqPyQwpMqcVoz.jpg,The Fast and the Furious Collection,190000000,Action|Crime|Thriller,168259,[US],en,Deckard Shaw seeks revenge against Dominic Tor...,9.5689,/ktofZ9Htrjiy0P6LEowsDaxd3Ri.jpg,...,138,False,العربية|English|Español|ภาษาไทย,Released,Vengeance hits home.,Furious 7,7.218,11363,190.0,1515.400000
9,/kIBK5SKwgqIIuRKhhWrJn3XkbPq.jpg,The Avengers Collection,235000000,Action|Adventure|Science Fiction,99861,[US],en,When Tony Stark tries to jumpstart a dormant p...,20.3748,/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg,...,141,False,English,Released,A new age has come.,Avengers: Age of Ultron,7.275,24611,235.0,1405.403694
10,/19Ed4XgjahPm4U8JT7SnntERIlt.jpg,Black Panther Collection,200000000,Action|Adventure|Science Fiction,284054,[US],en,"King T'Challa returns home to the reclusive, t...",12.7883,/uxzzxijgPIY7slzFvMotPv8wjKA.jpg,...,135,False,English|한국어/조선말|Kiswahili|,Released,Long live the king.,Black Panther,7.364,23619,200.0,1349.926083
11,/cbcpDn6XJaIGoOil1bKuskU8ds4.jpg,Harry Potter Collection,125000000,Adventure|Fantasy,12445,[GB],en,"Harry, Ron and Hermione continue their quest t...",10.3234,/c54HpQmuwXjHq2C9wmoACjxoom3.jpg,...,130,False,English,Released,It all ends.,Harry Potter and the Deathly Hallows: Part 2,8.080,22138,125.0,1341.511219
12,/bIUaCtWaRgd78SnoHJDI8TNf7Sd.jpg,Star Wars Collection,300000000,Adventure|Action|Science Fiction,181808,[US],en,Rey develops her newly discovered abilities wi...,20.2927,/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg,...,152,False,English,Released,Let the past die.,Star Wars: The Last Jedi,6.747,16444,300.0,1334.407706
13,/AoSZyb37ljMAxw0RdeQEBHKtgcc.jpg,Frozen Collection,150000000,Family|Animation|Adventure|Comedy|Fantasy,330457,[US],en,"Elsa, Anna, Kristoff and Olaf head far into th...",10.8444,/mINJaa34MtknCYl5AjtNJzWj8cD.jpg,...,103,False,English,Released,The past is not what it seems.,Frozen II,7.229,10346,150.0,1453.683476
14,/6WA9stUMbIkEPxn3D5SWlA8FIi7.jpg,Jurassic Park Collection,170000000,Adventure|Science Fiction|Thriller,351286,[US],en,Three years after Jurassic World was destroyed...,6.5699,/x2Us3jR6ToMJjbcPbLimYoxf6xr.jpg,...,129,False,English|Pусский,Released,The park is gone.,Jurassic World: Fallen Kingdom,6.531,12851,170.0,1310.469037
15,/rj58WQ9ImI0mYDptXdM7euX1Wjt.jpg,Frozen Collection,150000000,Animation|Family|Adventure|Fantasy,109445,[US],en,Young princess Anna of Arendelle dreams about ...,18.6585,/itAKcobTYGpYT8Phwjd8c9hleTo.jpg,...,102,False,English,Released,Who will save the day? The ice guy? The nice g...,Frozen,7.249,17677,150.0,1274.219009
16,/uU1Mt4JWhDvl4vKb3AfxNsorkoM.jpg,NaN,160000000,Family|Fantasy|Romance,321612,[US],en,A live-action adaptation of Disney's version o...,8.3216,/hKegSKIDep2ewJWPUQD7u0KqFIp.jpg,...,129,False,Français|English,Released,Be our guest.,Beauty and the Beast,7.000,16065,160.0,1266.115964
17,/mabuNsGJgRuCTuGqjFkWe1xdu19.jpg,The Incredibles Collection,200000000,Action|Adventure|Animation|Family,260513,[US],en,Elastigirl springs into action to save the day...,11.3073,/9lFKBtaVIhP7E2Pk0IY1CwTKTMZ.jpg,...,118,False,English,Released,"It's been too long, dahlings.",Incredibles 2,7.454,13773,200.0,1243.225667

In [34]:
movies.drop(columns=['status'], inplace = True)

In [35]:
movies.columns

Index(['backdrop_path', 'belongs_to_collection', 'budget', 'genres', 'id',
       'origin_country', 'original_language', 'overview', 'popularity',
       'poster_path', 'production_companies', 'production_countries',
       'release_date', 'revenue', 'runtime', 'softcore', 'spoken_languages',
       'tagline', 'title', 'vote_average', 'vote_count', 'budget_musd',
       'revenue_musd'],
      dtype='str')

**Reorder & Finalize DataFrame**

**10. Reorder columns:**

In [38]:
columns_order = ['id', 'title', 'tagline', 'release_date', 'genres', 'belongs_to_collection',
 'original_language', 'budget_musd', 'revenue_musd', 'production_companies',
 'production_countries', 'vote_count', 'vote_average', 'popularity', 'runtime',
 'overview', 'spoken_languages', 'poster_path']

In [39]:
movies = movies[columns_order]

**11. Reset index**

In [41]:
movies.reset_index(drop=True)

,id,title,tagline,release_date,genres,belongs_to_collection,original_language,budget_musd,revenue_musd,production_companies,production_countries,vote_count,vote_average,popularity,runtime,overview,spoken_languages,poster_path
0,299534,Avengers: Endgame,Avenge the fallen.,2019-04-24,Adventure|Science Fiction|Action,The Avengers Collection,en,356.0,2799.439100,Marvel Studios,United States of America,28042,8.239,13.9572,181,After the devastating events of Avengers: Infi...,English|日本語|,/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg
1,19995,Avatar,Enter the world of Pandora.,2009-12-16,Science Fiction|Action|Adventure,Avatar Collection,en,237.0,2923.706026,Dune Entertainment|Lightstorm Entertainment|20...,United States of America|United Kingdom,34234,7.609,15.0060,162,"In the 22nd century, a paraplegic Marine is di...",English|Español,/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg
2,140607,Star Wars: The Force Awakens,Every generation has a story.,2015-12-15,Adventure|Action|Science Fiction,Star Wars Collection,en,245.0,2068.223624,Lucasfilm Ltd.|Bad Robot,United States of America,20661,7.248,6.8790,136,Thirty years after defeating the Galactic Empi...,English,/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg
3,299536,Avengers: Infinity War,Destiny arrives all the same.,2018-04-25,Adventure|Action|Science Fiction,The Avengers Collection,en,300.0,2052.415039,Marvel Studios,United States of America,32298,8.239,22.6013,149,As the Avengers and their allies have continue...,English|,/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg
4,597,Titanic,Nothing on earth could come between them.,1997-12-18,Drama|Romance,NaN,en,200.0,2264.162353,Paramount Pictures|20th Century Fox|Lightstorm...,United States of America,27361,7.902,15.8007,194,101-year-old Rose DeWitt Bukater tells the sto...,English|Français|Deutsch|svenska|Italiano|Pусский,/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg
5,135397,Jurassic World,The park is open.,2015-06-06,Adventure|Science Fiction|Thriller,Jurassic Park Collection,en,150.0,1671.537444,Amblin Entertainment|Universal Pictures|Legend...,United States of America,21694,6.703,16.9054,124,Twenty-two years after the events of Jurassic ...,English,/rhr4y79GpxQF9IsfJItRXVaoGs4.jpg
6,420818,The Lion King,The king has returned.,2019-07-12,Adventure|Drama|Family|Animation,The Lion King (Reboot) Collection,en,260.0,1662.020819,Walt Disney Pictures|Fairview Entertainment,United States of America,10800,7.096,11.8006,118,"Simba idolizes his father, King Mufasa, and ta...",English,/dzBtMocZuJbjLOXvrl4zGYigDzh.jpg
7,24428,The Avengers,Some assembly required.,2012-04-25,Science Fiction|Action|Adventure,The Avengers Collection,en,220.0,1518.815515,Marvel Studios,United States of America,38785,8.057,27.1498,143,When an unexpected enemy emerges and threatens...,English|हिन्दी|Pусский,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg
8,168259,Furious 7,Vengeance hits home.,2015-04-01,Action|Crime|Thriller,The Fast and the Furious Collection,en,190.0,1515.400000,Original Film|One Race|Universal Pictures,United States of America,11363,7.218,9.5689,138,Deckard Shaw seeks revenge against Dominic Tor...,العربية|English|Español|ภาษาไทย,/ktofZ9Htrjiy0P6LEowsDaxd3Ri.jpg
9,99861,Avengers: Age of Ultron,A new age has come.,2015-04-22,Action|Adventure|Science Fiction,The Avengers Collection,en,235.0,1405.403694,Marvel Studios,United States of America,24611,7.275,20.3748,141,When Tony Stark tries to jumpstart a dormant p...,English,/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg
10,284054,Black Panther,Long live the king.,2018-02-13,Action|Adventure|Science Fiction,Black Panther Collection,en,200.0,1349.926083,Marvel Studios,United States of America,23619,7.364,12.7883,135,"King T'Challa returns home to the reclusive, t...",English|한국어/조선말|Kiswahili|,/uxzzxijgPIY7slzFvMotPv8wjKA.jpg
11,12445,Harry Potter and the Deathly Hallows: Part 2,It all ends.,2011-07-12,Adventure|Fantasy,Harry Potter Collection,en,125.0,1341.511219,Warner Bros. Pictures|Heyday Films,United Kingdom|United States of America,22138,8.080,10.3234,130,"Harry, Ron and Hermione continue their quest t...",English,/c54HpQmuwXjHq2C9wmoACjxoom3.jpg
12,181808,Star Wars: The Last Jedi,Let the past die.,2017-12-13,Adventure|Action|Science Fiction,Star Wars Collection,en,300.0,1334.407706,Lucasfilm Ltd.,United States of America,16444,6.747,20.2927,152,Rey develops her newly discovered abilities wi...,English,/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg
13,330457,Frozen II,The past is not what it seems.,2019-11-20,Family|Animation|Adventure|Comedy|Fantasy,Frozen Collection,en,150.0,1453.683476,Walt Disney Animation Studios,United States of America,10346,7.229,10.8444,103,"Elsa, Anna, Kristoff and Olaf head far into th...",English,/mINJaa34MtknCYl5AjtNJzWj8cD.jpg
14,351286,Jurassic World: Fallen Kingdom,The park is gone.,2018-06-06,Adventure|Science Fiction|Thriller,Jurassic Park Collection,en,170.0,1310.469037,Amblin Entertainment|Universal Pictures,United States of America,12851,6.531,6.5699,129,Three years after Jurassic World was destroyed...,English|Pусский,/x2Us3jR6ToMJjbcPbLimYoxf6xr.jpg
15,109445,Frozen,Who will save the day? The ice guy? The nice g...,2013-11-20,Animation|Family|Adventure|Fantasy,Frozen Collection,en,150.0,1274.219009,Walt Disney Animation Studios,United States of America,17677,7.249,18.6585,102,Young princess Anna of Arendelle dreams about ...,English,/itAKcobTYGpYT8Phwjd8c9hleTo.jpg
16,321612,Beauty and the Beast,Be our guest.,2017-03-16,Family|Fantasy|Romance,NaN,en,160.0,1266.115964,Walt Disney Pictures|Mandeville Films,United States of America,16065,7.000,8.3216,129,A live-action adaptation of Disney's version o...,Français|English,/hKegSKIDep2ewJWPUQD7u0KqFIp.jpg
17,260513,Incredibles 2,"It's been too long, dahlings.",2018-06-14,Action|Adventure|Animation|Family,The Incredibles Collection,en,200.0,1243.225667,Pixar,United States of America,13773,7.454,11.3073,118,Elastigirl springs into action to save the day...,English,/9lFKBtaVIhP7E2Pk0IY1CwTKTMZ.jpg

---

#### **Step 3: KPI Implementation & Analysis**

**Identify the Best/Worst Performing Movies**

In [71]:
movies.sort_values(by="revenue", ascending = False)

,backdrop_path,belongs_to_collection,budget,genres,id,origin_country,original_language,overview,popularity,poster_path,...,production_countries,release_date,revenue,runtime,softcore,spoken_languages,tagline,title,vote_average,vote_count
0,/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",356000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",299534,[US],en,After the devastating events of Avengers: Infi...,26.2998,/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2019-04-24,356000000,356000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Avenge the fallen.,Avengers: Endgame,8.239,28023
3,/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",300000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",299536,[US],en,As the Avengers and their allies have continue...,45.7180,/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2018-04-25,300000000,300000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Destiny arrives all the same.,Avengers: Infinity War,8.200,32279
12,/bIUaCtWaRgd78SnoHJDI8TNf7Sd.jpg,"{'id': 10, 'name': 'Star Wars Collection', 'po...",300000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",181808,[US],en,Rey develops her newly discovered abilities wi...,25.8659,/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2017-12-13,300000000,300000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Let the past die.,Star Wars: The Last Jedi,6.748,16437
6,/1TUg5pO1VZ4B0Q1amk3OlXvlpXV.jpg,"{'id': 762512, 'name': 'The Lion King (Reboot)...",260000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",420818,[US],en,"Simba idolizes his father, King Mufasa, and ta...",13.3553,/dzBtMocZuJbjLOXvrl4zGYigDzh.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2019-07-12,260000000,260000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",The king has returned.,The Lion King,7.096,10793
2,/k6EOrckWFuz7I4z4wiRwz8zsj4H.jpg,"{'id': 10, 'name': 'Star Wars Collection', 'po...",245000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",140607,[US],en,Thirty years after defeating the Galactic Empi...,12.3891,/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2015-12-15,245000000,245000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Every generation has a story.,Star Wars: The Force Awakens,7.248,20654
1,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,"{'id': 87096, 'name': 'Avatar Collection', 'po...",237000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",19995,[US],en,"In the 22nd century, a paraplegic Marine is di...",34.7960,/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2009-12-16,237000000,237000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Enter the world of Pandora.,Avatar,7.609,34221
9,/kIBK5SKwgqIIuRKhhWrJn3XkbPq.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",235000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",99861,[US],en,When Tony Stark tries to jumpstart a dormant p...,18.6505,/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2015-04-22,235000000,235000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",A new age has come.,Avengers: Age of Ultron,7.300,24599
7,/pGFQCp12a8andfPlpnmXz44IIvY.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",220000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",24428,[US],en,When an unexpected enemy emerges and threatens...,37.9454,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2012-04-25,220000000,220000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Some assembly required.,The Avengers,8.056,38752
10,/19Ed4XgjahPm4U8JT7SnntERIlt.jpg,"{'id': 529892, 'name': 'Black Panther Collecti...",200000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",284054,[US],en,"King T'Challa returns home to the reclusive, t...",15.8932,/uxzzxijgPIY7slzFvMotPv8wjKA.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2018-02-13,200000000,200000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Long live the king.,Black Panther,7.364,23610
4,/xnHVX37XZEp33hhCbYlQFq7ux1J.jpg,None,200000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",597,[US],en,101-year-old Rose DeWitt Bukater tells the sto...,31.7668,/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1997-12-18,200000000,200000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Nothing on earth could come between them.,Titanic,7.903,27345
17,/mabuNsGJgRuCTuGqjFkWe1xdu19.jpg,"{'id': 468222, 'name': 'The Incredibles Collec...",200000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",260513,[US],en,Elastigirl springs into action to save the day...,11.8054,/9lFKBtaVIhP7E2Pk0IY1CwTKTMZ.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2018-06-14,200000000,200000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...","It's been too long, dahlings.",Incredibles 2,7.454,13765
8,/ehzI1mVcnHqB58NqPyQwpMqcVoz.jpg,"{'id': 9485, 'name': 'The Fast and the Furious...",190000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",168259,[US],en,Deckard Shaw seeks revenge against Dominic Tor...,12.1149,/ktofZ9Htrjiy0P6LEowsDaxd3Ri.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2015-04-01,190000000,190000000,False,"[{'english_name': 'Arabic', 'iso_639_1': 'ar',...",Vengeance hits home.,Furious 7,7.219,11358
14,/6WA9stUMbIkEPxn3D5SWlA8FIi7.jpg,"{'id': 328, 'name': 'Jurassic Park Collection'...",170000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",351286,[US],en,Three years after Jurassic World was destroyed...,11.3360,/x2Us3jR6ToMJjbcPbLimYoxf6xr.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2018-06-06,170000000,170000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",The park is gone.,Jurassic World: Fallen Kingdom,6.531,12845
16,/uU1Mt4JWhDvl4vKb3AfxNsorkoM.jpg,None,160000000,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",321612,[US],en,A live-action adaptation of Disney's version o...,16.7348,/hKegSKIDep2ewJWPUQD7u0KqFIp.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2017-03-16,160000000,160000000,False,"[{'english_name': 'French', 'iso_639_1': 'fr',...",Be our guest.,Beauty and the Beast,6.967,16058
5,/dF6FjTZzRTENfB4R17HDN20jLT2.jpg,"{'id': 328, 'name': 'Jurassic Park Collection'...",150000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",135397,[US],en,Twenty-two years after the events of Jurassic ...,17.2889,/rhr4y79GpxQF9IsfJItRXVaoGs4.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2015-06-06,150000000,150000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",The park is open.,Jurassic World,6.702,21685
13,/AoSZyb37ljMAxw0RdeQEBHKtgcc.jpg,"{'id': 386382, 'name': 'Frozen Collection', 'p...",150000000,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",330457,[US],en,"Elsa, Anna, Kristoff and Olaf head far into th...",20.2003,/mINJaa34MtknCYl5AjtNJzWj8cD.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2019-11-20,150000000,150000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",The past is not what it seems.,Frozen II,7.229,10341
15,/rj58WQ9ImI0mYDptXdM7euX1Wjt.jpg,"{'id': 386382, 'name': 'Frozen Collection', 'p...",150000000,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",109445,[US],en,Young princess Anna of Arendelle dreams about ...,20.2458,/itAKcobTYGpYT8Phwjd8c9hleTo.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2013-11-20,150000000,150000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Who will save the day? The ice guy? The nice g...,Frozen,7.249,17665
11,/cbcpDn6XJaIGoOil1bKuskU8ds4.jpg,"{'id': 1241, 'name': 'Harry Potter Collection'...",125000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",12445,[GB],en,"Harry, Ron and Hermione continue their quest t...",16.3529,/c54HpQmuwXjHq2C9wmoACjxoom3.jpg,...,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",2011-07-12,125000000,125000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",It all ends.,Harry Potter and the Deathly Hallows: Part 2,8.081,22127

In [72]:
movies.sort_values(by='budget', ascending = False)

,backdrop_path,belongs_to_collection,budget,genres,id,origin_country,original_language,overview,popularity,poster_path,...,production_countries,release_date,revenue,runtime,softcore,spoken_languages,tagline,title,vote_average,vote_count
0,/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",356000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",299534,[US],en,After the devastating events of Avengers: Infi...,26.2998,/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2019-04-24,356000000,356000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Avenge the fallen.,Avengers: Endgame,8.239,28023
3,/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",300000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",299536,[US],en,As the Avengers and their allies have continue...,45.7180,/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2018-04-25,300000000,300000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Destiny arrives all the same.,Avengers: Infinity War,8.200,32279
12,/bIUaCtWaRgd78SnoHJDI8TNf7Sd.jpg,"{'id': 10, 'name': 'Star Wars Collection', 'po...",300000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",181808,[US],en,Rey develops her newly discovered abilities wi...,25.8659,/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2017-12-13,300000000,300000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Let the past die.,Star Wars: The Last Jedi,6.748,16437
6,/1TUg5pO1VZ4B0Q1amk3OlXvlpXV.jpg,"{'id': 762512, 'name': 'The Lion King (Reboot)...",260000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",420818,[US],en,"Simba idolizes his father, King Mufasa, and ta...",13.3553,/dzBtMocZuJbjLOXvrl4zGYigDzh.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2019-07-12,260000000,260000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",The king has returned.,The Lion King,7.096,10793
2,/k6EOrckWFuz7I4z4wiRwz8zsj4H.jpg,"{'id': 10, 'name': 'Star Wars Collection', 'po...",245000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",140607,[US],en,Thirty years after defeating the Galactic Empi...,12.3891,/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2015-12-15,245000000,245000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Every generation has a story.,Star Wars: The Force Awakens,7.248,20654
1,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,"{'id': 87096, 'name': 'Avatar Collection', 'po...",237000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",19995,[US],en,"In the 22nd century, a paraplegic Marine is di...",34.7960,/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2009-12-16,237000000,237000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Enter the world of Pandora.,Avatar,7.609,34221
9,/kIBK5SKwgqIIuRKhhWrJn3XkbPq.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",235000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",99861,[US],en,When Tony Stark tries to jumpstart a dormant p...,18.6505,/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2015-04-22,235000000,235000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",A new age has come.,Avengers: Age of Ultron,7.300,24599
7,/pGFQCp12a8andfPlpnmXz44IIvY.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",220000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",24428,[US],en,When an unexpected enemy emerges and threatens...,37.9454,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2012-04-25,220000000,220000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Some assembly required.,The Avengers,8.056,38752
10,/19Ed4XgjahPm4U8JT7SnntERIlt.jpg,"{'id': 529892, 'name': 'Black Panther Collecti...",200000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",284054,[US],en,"King T'Challa returns home to the reclusive, t...",15.8932,/uxzzxijgPIY7slzFvMotPv8wjKA.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2018-02-13,200000000,200000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Long live the king.,Black Panther,7.364,23610
4,/xnHVX37XZEp33hhCbYlQFq7ux1J.jpg,None,200000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",597,[US],en,101-year-old Rose DeWitt Bukater tells the sto...,31.7668,/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",1997-12-18,200000000,200000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Nothing on earth could come between them.,Titanic,7.903,27345
17,/mabuNsGJgRuCTuGqjFkWe1xdu19.jpg,"{'id': 468222, 'name': 'The Incredibles Collec...",200000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",260513,[US],en,Elastigirl springs into action to save the day...,11.8054,/9lFKBtaVIhP7E2Pk0IY1CwTKTMZ.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2018-06-14,200000000,200000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...","It's been too long, dahlings.",Incredibles 2,7.454,13765
8,/ehzI1mVcnHqB58NqPyQwpMqcVoz.jpg,"{'id': 9485, 'name': 'The Fast and the Furious...",190000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",168259,[US],en,Deckard Shaw seeks revenge against Dominic Tor...,12.1149,/ktofZ9Htrjiy0P6LEowsDaxd3Ri.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2015-04-01,190000000,190000000,False,"[{'english_name': 'Arabic', 'iso_639_1': 'ar',...",Vengeance hits home.,Furious 7,7.219,11358
14,/6WA9stUMbIkEPxn3D5SWlA8FIi7.jpg,"{'id': 328, 'name': 'Jurassic Park Collection'...",170000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",351286,[US],en,Three years after Jurassic World was destroyed...,11.3360,/x2Us3jR6ToMJjbcPbLimYoxf6xr.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2018-06-06,170000000,170000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",The park is gone.,Jurassic World: Fallen Kingdom,6.531,12845
16,/uU1Mt4JWhDvl4vKb3AfxNsorkoM.jpg,None,160000000,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",321612,[US],en,A live-action adaptation of Disney's version o...,16.7348,/hKegSKIDep2ewJWPUQD7u0KqFIp.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2017-03-16,160000000,160000000,False,"[{'english_name': 'French', 'iso_639_1': 'fr',...",Be our guest.,Beauty and the Beast,6.967,16058
5,/dF6FjTZzRTENfB4R17HDN20jLT2.jpg,"{'id': 328, 'name': 'Jurassic Park Collection'...",150000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",135397,[US],en,Twenty-two years after the events of Jurassic ...,17.2889,/rhr4y79GpxQF9IsfJItRXVaoGs4.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2015-06-06,150000000,150000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",The park is open.,Jurassic World,6.702,21685
13,/AoSZyb37ljMAxw0RdeQEBHKtgcc.jpg,"{'id': 386382, 'name': 'Frozen Collection', 'p...",150000000,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",330457,[US],en,"Elsa, Anna, Kristoff and Olaf head far into th...",20.2003,/mINJaa34MtknCYl5AjtNJzWj8cD.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2019-11-20,150000000,150000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",The past is not what it seems.,Frozen II,7.229,10341
15,/rj58WQ9ImI0mYDptXdM7euX1Wjt.jpg,"{'id': 386382, 'name': 'Frozen Collection', 'p...",150000000,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",109445,[US],en,Young princess Anna of Arendelle dreams about ...,20.2458,/itAKcobTYGpYT8Phwjd8c9hleTo.jpg,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",2013-11-20,150000000,150000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Who will save the day? The ice guy? The nice g...,Frozen,7.249,17665
11,/cbcpDn6XJaIGoOil1bKuskU8ds4.jpg,"{'id': 1241, 'name': 'Harry Potter Collection'...",125000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",12445,[GB],en,"Harry, Ron and Hermione continue their quest t...",16.3529,/c54HpQmuwXjHq2C9wmoACjxoom3.jpg,...,"[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",2011-07-12,125000000,125000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",It all ends.,Harry Potter and the Deathly Hallows: Part 2,8.081,22127

In [73]:
movies['profit'] = movies['revenue'] - movies['budget']

In [74]:
movies.sort_values(by="profit", ascending = False)

,backdrop_path,belongs_to_collection,budget,genres,id,origin_country,original_language,overview,popularity,poster_path,...,release_date,revenue,runtime,softcore,spoken_languages,tagline,title,vote_average,vote_count,profit
0,/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",356000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",299534,[US],en,After the devastating events of Avengers: Infi...,26.2998,/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg,...,2019-04-24,356000000,356000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Avenge the fallen.,Avengers: Endgame,8.239,28023,0
1,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,"{'id': 87096, 'name': 'Avatar Collection', 'po...",237000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",19995,[US],en,"In the 22nd century, a paraplegic Marine is di...",34.7960,/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg,...,2009-12-16,237000000,237000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Enter the world of Pandora.,Avatar,7.609,34221,0
2,/k6EOrckWFuz7I4z4wiRwz8zsj4H.jpg,"{'id': 10, 'name': 'Star Wars Collection', 'po...",245000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",140607,[US],en,Thirty years after defeating the Galactic Empi...,12.3891,/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg,...,2015-12-15,245000000,245000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Every generation has a story.,Star Wars: The Force Awakens,7.248,20654,0
3,/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",300000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",299536,[US],en,As the Avengers and their allies have continue...,45.7180,/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg,...,2018-04-25,300000000,300000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Destiny arrives all the same.,Avengers: Infinity War,8.200,32279,0
4,/xnHVX37XZEp33hhCbYlQFq7ux1J.jpg,None,200000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",597,[US],en,101-year-old Rose DeWitt Bukater tells the sto...,31.7668,/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg,...,1997-12-18,200000000,200000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Nothing on earth could come between them.,Titanic,7.903,27345,0
5,/dF6FjTZzRTENfB4R17HDN20jLT2.jpg,"{'id': 328, 'name': 'Jurassic Park Collection'...",150000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",135397,[US],en,Twenty-two years after the events of Jurassic ...,17.2889,/rhr4y79GpxQF9IsfJItRXVaoGs4.jpg,...,2015-06-06,150000000,150000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",The park is open.,Jurassic World,6.702,21685,0
6,/1TUg5pO1VZ4B0Q1amk3OlXvlpXV.jpg,"{'id': 762512, 'name': 'The Lion King (Reboot)...",260000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",420818,[US],en,"Simba idolizes his father, King Mufasa, and ta...",13.3553,/dzBtMocZuJbjLOXvrl4zGYigDzh.jpg,...,2019-07-12,260000000,260000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",The king has returned.,The Lion King,7.096,10793,0
7,/pGFQCp12a8andfPlpnmXz44IIvY.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",220000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",24428,[US],en,When an unexpected enemy emerges and threatens...,37.9454,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,...,2012-04-25,220000000,220000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Some assembly required.,The Avengers,8.056,38752,0
8,/ehzI1mVcnHqB58NqPyQwpMqcVoz.jpg,"{'id': 9485, 'name': 'The Fast and the Furious...",190000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",168259,[US],en,Deckard Shaw seeks revenge against Dominic Tor...,12.1149,/ktofZ9Htrjiy0P6LEowsDaxd3Ri.jpg,...,2015-04-01,190000000,190000000,False,"[{'english_name': 'Arabic', 'iso_639_1': 'ar',...",Vengeance hits home.,Furious 7,7.219,11358,0
9,/kIBK5SKwgqIIuRKhhWrJn3XkbPq.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",235000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",99861,[US],en,When Tony Stark tries to jumpstart a dormant p...,18.6505,/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg,...,2015-04-22,235000000,235000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",A new age has come.,Avengers: Age of Ultron,7.300,24599,0
10,/19Ed4XgjahPm4U8JT7SnntERIlt.jpg,"{'id': 529892, 'name': 'Black Panther Collecti...",200000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",284054,[US],en,"King T'Challa returns home to the reclusive, t...",15.8932,/uxzzxijgPIY7slzFvMotPv8wjKA.jpg,...,2018-02-13,200000000,200000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Long live the king.,Black Panther,7.364,23610,0
11,/cbcpDn6XJaIGoOil1bKuskU8ds4.jpg,"{'id': 1241, 'name': 'Harry Potter Collection'...",125000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",12445,[GB],en,"Harry, Ron and Hermione continue their quest t...",16.3529,/c54HpQmuwXjHq2C9wmoACjxoom3.jpg,...,2011-07-12,125000000,125000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",It all ends.,Harry Potter and the Deathly Hallows: Part 2,8.081,22127,0
12,/bIUaCtWaRgd78SnoHJDI8TNf7Sd.jpg,"{'id': 10, 'name': 'Star Wars Collection', 'po...",300000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",181808,[US],en,Rey develops her newly discovered abilities wi...,25.8659,/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg,...,2017-12-13,300000000,300000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Let the past die.,Star Wars: The Last Jedi,6.748,16437,0
13,/AoSZyb37ljMAxw0RdeQEBHKtgcc.jpg,"{'id': 386382, 'name': 'Frozen Collection', 'p...",150000000,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",330457,[US],en,"Elsa, Anna, Kristoff and Olaf head far into th...",20.2003,/mINJaa34MtknCYl5AjtNJzWj8cD.jpg,...,2019-11-20,150000000,150000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",The past is not what it seems.,Frozen II,7.229,10341,0
14,/6WA9stUMbIkEPxn3D5SWlA8FIi7.jpg,"{'id': 328, 'name': 'Jurassic Park Collection'...",170000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",351286,[US],en,Three years after Jurassic World was destroyed...,11.3360,/x2Us3jR6ToMJjbcPbLimYoxf6xr.jpg,...,2018-06-06,170000000,170000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",The park is gone.,Jurassic World: Fallen Kingdom,6.531,12845,0
15,/rj58WQ9ImI0mYDptXdM7euX1Wjt.jpg,"{'id': 386382, 'name': 'Frozen Collection', 'p...",150000000,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",109445,[US],en,Young princess Anna of Arendelle dreams about ...,20.2458,/itAKcobTYGpYT8Phwjd8c9hleTo.jpg,...,2013-11-20,150000000,150000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Who will save the day? The ice guy? The nice g...,Frozen,7.249,17665,0
16,/uU1Mt4JWhDvl4vKb3AfxNsorkoM.jpg,None,160000000,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",321612,[US],en,A live-action adaptation of Disney's version o...,16.7348,/hKegSKIDep2ewJWPUQD7u0KqFIp.jpg,...,2017-03-16,160000000,160000000,False,"[{'english_name': 'French', 'iso_639_1': 'fr',...",Be our guest.,Beauty and the Beast,6.967,16058,0
17,/mabuNsGJgRuCTuGqjFkWe1xdu19.jpg,"{'id': 468222, 'name': 'The Incredibles Collec...",200000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",260513,[US],en,Elastigirl springs into action to save the day...,11.8054,/9lFKBtaVIhP7E2Pk0IY1CwTKTMZ.jpg,...,2018-06-14,200000000,200000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...","It's been too long, dahlings.",Incredibles 2,7.454,13765,0

In [75]:
movies.sort_values(by="vote_count", ascending = False)

,backdrop_path,belongs_to_collection,budget,genres,id,origin_country,original_language,overview,popularity,poster_path,...,release_date,revenue,runtime,softcore,spoken_languages,tagline,title,vote_average,vote_count,profit
7,/pGFQCp12a8andfPlpnmXz44IIvY.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",220000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",24428,[US],en,When an unexpected enemy emerges and threatens...,37.9454,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,...,2012-04-25,220000000,220000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Some assembly required.,The Avengers,8.056,38752,0
1,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,"{'id': 87096, 'name': 'Avatar Collection', 'po...",237000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",19995,[US],en,"In the 22nd century, a paraplegic Marine is di...",34.7960,/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg,...,2009-12-16,237000000,237000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Enter the world of Pandora.,Avatar,7.609,34221,0
3,/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",300000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",299536,[US],en,As the Avengers and their allies have continue...,45.7180,/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg,...,2018-04-25,300000000,300000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Destiny arrives all the same.,Avengers: Infinity War,8.200,32279,0
0,/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",356000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",299534,[US],en,After the devastating events of Avengers: Infi...,26.2998,/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg,...,2019-04-24,356000000,356000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Avenge the fallen.,Avengers: Endgame,8.239,28023,0
4,/xnHVX37XZEp33hhCbYlQFq7ux1J.jpg,None,200000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",597,[US],en,101-year-old Rose DeWitt Bukater tells the sto...,31.7668,/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg,...,1997-12-18,200000000,200000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Nothing on earth could come between them.,Titanic,7.903,27345,0
9,/kIBK5SKwgqIIuRKhhWrJn3XkbPq.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",235000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",99861,[US],en,When Tony Stark tries to jumpstart a dormant p...,18.6505,/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg,...,2015-04-22,235000000,235000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",A new age has come.,Avengers: Age of Ultron,7.300,24599,0
10,/19Ed4XgjahPm4U8JT7SnntERIlt.jpg,"{'id': 529892, 'name': 'Black Panther Collecti...",200000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",284054,[US],en,"King T'Challa returns home to the reclusive, t...",15.8932,/uxzzxijgPIY7slzFvMotPv8wjKA.jpg,...,2018-02-13,200000000,200000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Long live the king.,Black Panther,7.364,23610,0
11,/cbcpDn6XJaIGoOil1bKuskU8ds4.jpg,"{'id': 1241, 'name': 'Harry Potter Collection'...",125000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",12445,[GB],en,"Harry, Ron and Hermione continue their quest t...",16.3529,/c54HpQmuwXjHq2C9wmoACjxoom3.jpg,...,2011-07-12,125000000,125000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",It all ends.,Harry Potter and the Deathly Hallows: Part 2,8.081,22127,0
5,/dF6FjTZzRTENfB4R17HDN20jLT2.jpg,"{'id': 328, 'name': 'Jurassic Park Collection'...",150000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",135397,[US],en,Twenty-two years after the events of Jurassic ...,17.2889,/rhr4y79GpxQF9IsfJItRXVaoGs4.jpg,...,2015-06-06,150000000,150000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",The park is open.,Jurassic World,6.702,21685,0
2,/k6EOrckWFuz7I4z4wiRwz8zsj4H.jpg,"{'id': 10, 'name': 'Star Wars Collection', 'po...",245000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",140607,[US],en,Thirty years after defeating the Galactic Empi...,12.3891,/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg,...,2015-12-15,245000000,245000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Every generation has a story.,Star Wars: The Force Awakens,7.248,20654,0
15,/rj58WQ9ImI0mYDptXdM7euX1Wjt.jpg,"{'id': 386382, 'name': 'Frozen Collection', 'p...",150000000,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",109445,[US],en,Young princess Anna of Arendelle dreams about ...,20.2458,/itAKcobTYGpYT8Phwjd8c9hleTo.jpg,...,2013-11-20,150000000,150000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Who will save the day? The ice guy? The nice g...,Frozen,7.249,17665,0
12,/bIUaCtWaRgd78SnoHJDI8TNf7Sd.jpg,"{'id': 10, 'name': 'Star Wars Collection', 'po...",300000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",181808,[US],en,Rey develops her newly discovered abilities wi...,25.8659,/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg,...,2017-12-13,300000000,300000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Let the past die.,Star Wars: The Last Jedi,6.748,16437,0
16,/uU1Mt4JWhDvl4vKb3AfxNsorkoM.jpg,None,160000000,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",321612,[US],en,A live-action adaptation of Disney's version o...,16.7348,/hKegSKIDep2ewJWPUQD7u0KqFIp.jpg,...,2017-03-16,160000000,160000000,False,"[{'english_name': 'French', 'iso_639_1': 'fr',...",Be our guest.,Beauty and the Beast,6.967,16058,0
17,/mabuNsGJgRuCTuGqjFkWe1xdu19.jpg,"{'id': 468222, 'name': 'The Incredibles Collec...",200000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",260513,[US],en,Elastigirl springs into action to save the day...,11.8054,/9lFKBtaVIhP7E2Pk0IY1CwTKTMZ.jpg,...,2018-06-14,200000000,200000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...","It's been too long, dahlings.",Incredibles 2,7.454,13765,0
14,/6WA9stUMbIkEPxn3D5SWlA8FIi7.jpg,"{'id': 328, 'name': 'Jurassic Park Collection'...",170000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",351286,[US],en,Three years after Jurassic World was destroyed...,11.3360,/x2Us3jR6ToMJjbcPbLimYoxf6xr.jpg,...,2018-06-06,170000000,170000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",The park is gone.,Jurassic World: Fallen Kingdom,6.531,12845,0
8,/ehzI1mVcnHqB58NqPyQwpMqcVoz.jpg,"{'id': 9485, 'name': 'The Fast and the Furious...",190000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",168259,[US],en,Deckard Shaw seeks revenge against Dominic Tor...,12.1149,/ktofZ9Htrjiy0P6LEowsDaxd3Ri.jpg,...,2015-04-01,190000000,190000000,False,"[{'english_name': 'Arabic', 'iso_639_1': 'ar',...",Vengeance hits home.,Furious 7,7.219,11358,0
6,/1TUg5pO1VZ4B0Q1amk3OlXvlpXV.jpg,"{'id': 762512, 'name': 'The Lion King (Reboot)...",260000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",420818,[US],en,"Simba idolizes his father, King Mufasa, and ta...",13.3553,/dzBtMocZuJbjLOXvrl4zGYigDzh.jpg,...,2019-07-12,260000000,260000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",The king has returned.,The Lion King,7.096,10793,0
13,/AoSZyb37ljMAxw0RdeQEBHKtgcc.jpg,"{'id': 386382, 'name': 'Frozen Collection', 'p...",150000000,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",330457,[US],en,"Elsa, Anna, Kristoff and Olaf head far into th...",20.2003,/mINJaa34MtknCYl5AjtNJzWj8cD.jpg,...,2019-11-20,150000000,150000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",The past is not what it seems.,Frozen II,7.229,10341,0

In [77]:
movies[movies['vote_count'] >= 10]

,backdrop_path,belongs_to_collection,budget,genres,id,origin_country,original_language,overview,popularity,poster_path,...,release_date,revenue,runtime,softcore,spoken_languages,tagline,title,vote_average,vote_count,profit
0,/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",356000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",299534,[US],en,After the devastating events of Avengers: Infi...,26.2998,/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg,...,2019-04-24,356000000,356000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Avenge the fallen.,Avengers: Endgame,8.239,28023,0
1,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,"{'id': 87096, 'name': 'Avatar Collection', 'po...",237000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",19995,[US],en,"In the 22nd century, a paraplegic Marine is di...",34.7960,/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg,...,2009-12-16,237000000,237000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Enter the world of Pandora.,Avatar,7.609,34221,0
2,/k6EOrckWFuz7I4z4wiRwz8zsj4H.jpg,"{'id': 10, 'name': 'Star Wars Collection', 'po...",245000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",140607,[US],en,Thirty years after defeating the Galactic Empi...,12.3891,/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg,...,2015-12-15,245000000,245000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Every generation has a story.,Star Wars: The Force Awakens,7.248,20654,0
3,/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",300000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",299536,[US],en,As the Avengers and their allies have continue...,45.7180,/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg,...,2018-04-25,300000000,300000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Destiny arrives all the same.,Avengers: Infinity War,8.200,32279,0
4,/xnHVX37XZEp33hhCbYlQFq7ux1J.jpg,None,200000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",597,[US],en,101-year-old Rose DeWitt Bukater tells the sto...,31.7668,/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg,...,1997-12-18,200000000,200000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Nothing on earth could come between them.,Titanic,7.903,27345,0
5,/dF6FjTZzRTENfB4R17HDN20jLT2.jpg,"{'id': 328, 'name': 'Jurassic Park Collection'...",150000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",135397,[US],en,Twenty-two years after the events of Jurassic ...,17.2889,/rhr4y79GpxQF9IsfJItRXVaoGs4.jpg,...,2015-06-06,150000000,150000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",The park is open.,Jurassic World,6.702,21685,0
6,/1TUg5pO1VZ4B0Q1amk3OlXvlpXV.jpg,"{'id': 762512, 'name': 'The Lion King (Reboot)...",260000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",420818,[US],en,"Simba idolizes his father, King Mufasa, and ta...",13.3553,/dzBtMocZuJbjLOXvrl4zGYigDzh.jpg,...,2019-07-12,260000000,260000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",The king has returned.,The Lion King,7.096,10793,0
7,/pGFQCp12a8andfPlpnmXz44IIvY.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",220000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",24428,[US],en,When an unexpected enemy emerges and threatens...,37.9454,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,...,2012-04-25,220000000,220000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Some assembly required.,The Avengers,8.056,38752,0
8,/ehzI1mVcnHqB58NqPyQwpMqcVoz.jpg,"{'id': 9485, 'name': 'The Fast and the Furious...",190000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",168259,[US],en,Deckard Shaw seeks revenge against Dominic Tor...,12.1149,/ktofZ9Htrjiy0P6LEowsDaxd3Ri.jpg,...,2015-04-01,190000000,190000000,False,"[{'english_name': 'Arabic', 'iso_639_1': 'ar',...",Vengeance hits home.,Furious 7,7.219,11358,0
9,/kIBK5SKwgqIIuRKhhWrJn3XkbPq.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",235000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",99861,[US],en,When Tony Stark tries to jumpstart a dormant p...,18.6505,/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg,...,2015-04-22,235000000,235000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",A new age has come.,Avengers: Age of Ultron,7.300,24599,0
10,/19Ed4XgjahPm4U8JT7SnntERIlt.jpg,"{'id': 529892, 'name': 'Black Panther Collecti...",200000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",284054,[US],en,"King T'Challa returns home to the reclusive, t...",15.8932,/uxzzxijgPIY7slzFvMotPv8wjKA.jpg,...,2018-02-13,200000000,200000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Long live the king.,Black Panther,7.364,23610,0
11,/cbcpDn6XJaIGoOil1bKuskU8ds4.jpg,"{'id': 1241, 'name': 'Harry Potter Collection'...",125000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",12445,[GB],en,"Harry, Ron and Hermione continue their quest t...",16.3529,/c54HpQmuwXjHq2C9wmoACjxoom3.jpg,...,2011-07-12,125000000,125000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",It all ends.,Harry Potter and the Deathly Hallows: Part 2,8.081,22127,0
12,/bIUaCtWaRgd78SnoHJDI8TNf7Sd.jpg,"{'id': 10, 'name': 'Star Wars Collection', 'po...",300000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",181808,[US],en,Rey develops her newly discovered abilities wi...,25.8659,/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg,...,2017-12-13,300000000,300000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Let the past die.,Star Wars: The Last Jedi,6.748,16437,0
13,/AoSZyb37ljMAxw0RdeQEBHKtgcc.jpg,"{'id': 386382, 'name': 'Frozen Collection', 'p...",150000000,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",330457,[US],en,"Elsa, Anna, Kristoff and Olaf head far into th...",20.2003,/mINJaa34MtknCYl5AjtNJzWj8cD.jpg,...,2019-11-20,150000000,150000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",The past is not what it seems.,Frozen II,7.229,10341,0
14,/6WA9stUMbIkEPxn3D5SWlA8FIi7.jpg,"{'id': 328, 'name': 'Jurassic Park Collection'...",170000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",351286,[US],en,Three years after Jurassic World was destroyed...,11.3360,/x2Us3jR6ToMJjbcPbLimYoxf6xr.jpg,...,2018-06-06,170000000,170000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",The park is gone.,Jurassic World: Fallen Kingdom,6.531,12845,0
15,/rj58WQ9ImI0mYDptXdM7euX1Wjt.jpg,"{'id': 386382, 'name': 'Frozen Collection', 'p...",150000000,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",109445,[US],en,Young princess Anna of Arendelle dreams about ...,20.2458,/itAKcobTYGpYT8Phwjd8c9hleTo.jpg,...,2013-11-20,150000000,150000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Who will save the day? The ice guy? The nice g...,Frozen,7.249,17665,0
16,/uU1Mt4JWhDvl4vKb3AfxNsorkoM.jpg,None,160000000,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",321612,[US],en,A live-action adaptation of Disney's version o...,16.7348,/hKegSKIDep2ewJWPUQD7u0KqFIp.jpg,...,2017-03-16,160000000,160000000,False,"[{'english_name': 'French', 'iso_639_1': 'fr',...",Be our guest.,Beauty and the Beast,6.967,16058,0
17,/mabuNsGJgRuCTuGqjFkWe1xdu19.jpg,"{'id': 468222, 'name': 'The Incredibles Collec...",200000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",260513,[US],en,Elastigirl springs into action to save the day...,11.8054,/9lFKBtaVIhP7E2Pk0IY1CwTKTMZ.jpg,...,2018-06-14,200000000,200000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...","It's been too long, dahlings.",Incredibles 2,7.454,13765,0

In [78]:
movies[movies['vote_count'] < 10]

Empty DataFrame
Columns: [backdrop_path, belongs_to_collection, budget, genres, id, origin_country, original_language, overview, popularity, poster_path, production_companies, production_countries, release_date, revenue, runtime, softcore, spoken_languages, tagline, title, vote_average, vote_count, profit]
Index: []

[0 rows x 22 columns]

In [79]:
movies.sort_values(by='popularity', ascending = False)

,backdrop_path,belongs_to_collection,budget,genres,id,origin_country,original_language,overview,popularity,poster_path,...,release_date,revenue,runtime,softcore,spoken_languages,tagline,title,vote_average,vote_count,profit
3,/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",300000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",299536,[US],en,As the Avengers and their allies have continue...,45.7180,/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg,...,2018-04-25,300000000,300000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Destiny arrives all the same.,Avengers: Infinity War,8.200,32279,0
7,/pGFQCp12a8andfPlpnmXz44IIvY.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",220000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",24428,[US],en,When an unexpected enemy emerges and threatens...,37.9454,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,...,2012-04-25,220000000,220000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Some assembly required.,The Avengers,8.056,38752,0
1,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,"{'id': 87096, 'name': 'Avatar Collection', 'po...",237000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",19995,[US],en,"In the 22nd century, a paraplegic Marine is di...",34.7960,/gKY6q7SjCkAU6FqvqWybDYgUKIF.jpg,...,2009-12-16,237000000,237000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Enter the world of Pandora.,Avatar,7.609,34221,0
4,/xnHVX37XZEp33hhCbYlQFq7ux1J.jpg,None,200000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",597,[US],en,101-year-old Rose DeWitt Bukater tells the sto...,31.7668,/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg,...,1997-12-18,200000000,200000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Nothing on earth could come between them.,Titanic,7.903,27345,0
0,/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",356000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",299534,[US],en,After the devastating events of Avengers: Infi...,26.2998,/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg,...,2019-04-24,356000000,356000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Avenge the fallen.,Avengers: Endgame,8.239,28023,0
12,/bIUaCtWaRgd78SnoHJDI8TNf7Sd.jpg,"{'id': 10, 'name': 'Star Wars Collection', 'po...",300000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",181808,[US],en,Rey develops her newly discovered abilities wi...,25.8659,/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg,...,2017-12-13,300000000,300000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Let the past die.,Star Wars: The Last Jedi,6.748,16437,0
15,/rj58WQ9ImI0mYDptXdM7euX1Wjt.jpg,"{'id': 386382, 'name': 'Frozen Collection', 'p...",150000000,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",109445,[US],en,Young princess Anna of Arendelle dreams about ...,20.2458,/itAKcobTYGpYT8Phwjd8c9hleTo.jpg,...,2013-11-20,150000000,150000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Who will save the day? The ice guy? The nice g...,Frozen,7.249,17665,0
13,/AoSZyb37ljMAxw0RdeQEBHKtgcc.jpg,"{'id': 386382, 'name': 'Frozen Collection', 'p...",150000000,"[{'id': 10751, 'name': 'Family'}, {'id': 16, '...",330457,[US],en,"Elsa, Anna, Kristoff and Olaf head far into th...",20.2003,/mINJaa34MtknCYl5AjtNJzWj8cD.jpg,...,2019-11-20,150000000,150000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",The past is not what it seems.,Frozen II,7.229,10341,0
9,/kIBK5SKwgqIIuRKhhWrJn3XkbPq.jpg,"{'id': 86311, 'name': 'The Avengers Collection...",235000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",99861,[US],en,When Tony Stark tries to jumpstart a dormant p...,18.6505,/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg,...,2015-04-22,235000000,235000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",A new age has come.,Avengers: Age of Ultron,7.300,24599,0
5,/dF6FjTZzRTENfB4R17HDN20jLT2.jpg,"{'id': 328, 'name': 'Jurassic Park Collection'...",150000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",135397,[US],en,Twenty-two years after the events of Jurassic ...,17.2889,/rhr4y79GpxQF9IsfJItRXVaoGs4.jpg,...,2015-06-06,150000000,150000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",The park is open.,Jurassic World,6.702,21685,0
16,/uU1Mt4JWhDvl4vKb3AfxNsorkoM.jpg,None,160000000,"[{'id': 10751, 'name': 'Family'}, {'id': 14, '...",321612,[US],en,A live-action adaptation of Disney's version o...,16.7348,/hKegSKIDep2ewJWPUQD7u0KqFIp.jpg,...,2017-03-16,160000000,160000000,False,"[{'english_name': 'French', 'iso_639_1': 'fr',...",Be our guest.,Beauty and the Beast,6.967,16058,0
11,/cbcpDn6XJaIGoOil1bKuskU8ds4.jpg,"{'id': 1241, 'name': 'Harry Potter Collection'...",125000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",12445,[GB],en,"Harry, Ron and Hermione continue their quest t...",16.3529,/c54HpQmuwXjHq2C9wmoACjxoom3.jpg,...,2011-07-12,125000000,125000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",It all ends.,Harry Potter and the Deathly Hallows: Part 2,8.081,22127,0
10,/19Ed4XgjahPm4U8JT7SnntERIlt.jpg,"{'id': 529892, 'name': 'Black Panther Collecti...",200000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",284054,[US],en,"King T'Challa returns home to the reclusive, t...",15.8932,/uxzzxijgPIY7slzFvMotPv8wjKA.jpg,...,2018-02-13,200000000,200000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Long live the king.,Black Panther,7.364,23610,0
6,/1TUg5pO1VZ4B0Q1amk3OlXvlpXV.jpg,"{'id': 762512, 'name': 'The Lion King (Reboot)...",260000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",420818,[US],en,"Simba idolizes his father, King Mufasa, and ta...",13.3553,/dzBtMocZuJbjLOXvrl4zGYigDzh.jpg,...,2019-07-12,260000000,260000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",The king has returned.,The Lion King,7.096,10793,0
2,/k6EOrckWFuz7I4z4wiRwz8zsj4H.jpg,"{'id': 10, 'name': 'Star Wars Collection', 'po...",245000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",140607,[US],en,Thirty years after defeating the Galactic Empi...,12.3891,/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg,...,2015-12-15,245000000,245000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",Every generation has a story.,Star Wars: The Force Awakens,7.248,20654,0
8,/ehzI1mVcnHqB58NqPyQwpMqcVoz.jpg,"{'id': 9485, 'name': 'The Fast and the Furious...",190000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",168259,[US],en,Deckard Shaw seeks revenge against Dominic Tor...,12.1149,/ktofZ9Htrjiy0P6LEowsDaxd3Ri.jpg,...,2015-04-01,190000000,190000000,False,"[{'english_name': 'Arabic', 'iso_639_1': 'ar',...",Vengeance hits home.,Furious 7,7.219,11358,0
17,/mabuNsGJgRuCTuGqjFkWe1xdu19.jpg,"{'id': 468222, 'name': 'The Incredibles Collec...",200000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",260513,[US],en,Elastigirl springs into action to save the day...,11.8054,/9lFKBtaVIhP7E2Pk0IY1CwTKTMZ.jpg,...,2018-06-14,200000000,200000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...","It's been too long, dahlings.",Incredibles 2,7.454,13765,0
14,/6WA9stUMbIkEPxn3D5SWlA8FIi7.jpg,"{'id': 328, 'name': 'Jurassic Park Collection'...",170000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 878, ...",351286,[US],en,Three years after Jurassic World was destroyed...,11.3360,/x2Us3jR6ToMJjbcPbLimYoxf6xr.jpg,...,2018-06-06,170000000,170000000,False,"[{'english_name': 'English', 'iso_639_1': 'en'...",The park is gone.,Jurassic World: Fallen Kingdom,6.531,12845,0

**Advanced movie filtering & search queries**

## Step 4: Data Visualization